### ISSUE TITLE
Describing API attributes

### ISSUE THREAD

**Issue by rhc54** [pmix/pmix-standard#11]
Did we ever settle on a common method for laying out the attributes for a given API?

Designating which ones are "optional" vs those that really must be "supported"?

I need to provide a broader description for the PMIx_Notify_event API, and there are a list of attributes that we want to see provided - need to figure out how we present those in the standard.

**Comment by jjhursey** [comment]
For 'required' attributes we should add some language in the Structures/Datatypes chapter noting that some interfaces require support for some attributes. Instead of the blanket language of all attributes are optional.

**Comment by rhc54** [comment]
@jjhursey When I paste an attribute item, there are times when I need to add some clarifying text for that particular usage. If I just add it to the end of the paste directive, it gets put in as a separate paragraph thus making it unclear. Any ideas on how to get around this?

Example:
```
\pasteAttributeItem{PMIX_GDS_MODULE} This attribute controls only the selection of
GDS module for internal use by the process. Module selection for interacting with the
server is performed dynamically during the connection process.
```
comes out as
```
PMIX_GDS_MODULE "pmix.gds.mod" (char*)
     Comma-delimited string of desired modules.

This attribute controls only the selection of GDS module for internal use by the process. Module
selection for interacting with the server is performed dynamically during the connection process.
```
What I would like to see:
```
PMIX_GDS_MODULE "pmix.gds.mod" (char*)
    Comma-delimited string of desired modules. This attribute controls only the selection of
    GDS module for internal use by the process. Module selection for interacting with the server
    is performed dynamically during the connection process.
```

**Comment by rhc54** [comment]
This works beautifully - thanks!
