### ISSUE TITLE
Collective algorithm parameter in Fence

### ISSUE THREAD

**Issue by artpol84** [pmix/pmix-standard#110]
The following statement:
"PMIX_COLLECTIVE_ALGO{"pmix.calgo"}{char*} Comma-delimited list of algorithms to use for the collective operation." ([link](https://github.com/pmix/pmix-standard/blob/0936a60c93b0e6bce09f480263f63fee0d2c8406/Chap_API_Struct.tex#L2992)) states that the user may request a specific algorithm from the RM.

It is not clear what is the naming scheme for the algorithms. What RM should expect to get as the input?

**Comment by rhc54** [comment]
@artpol84 Please see what you think - #113
