### ISSUE TITLE
Terms "namespace" and "job" and their relation

### ISSUE THREAD

**Issue by artpol84** [pmix/pmix-standard#121]
I found the following definitions conflicting:
```
PMIX_NSPACE "pmix.nspace" (char*)
    Namespace of the job.
...
PMIX_UNIV_SIZE "pmix.univ.size" (uint32_t)
    Number of processes in this namespace.
PMIX_JOB_SIZE "pmix.job.size" (uint32_t)
    Number of processes in this job
```
In my understanding job and namespace have the same scope. PMIx namespace is the way to describe the job.
Given that why would we have `UNIV_SIZE` and `JOB_SIZE` to be different in the way the description is provided?
Logically UNIVERSE size is the size of the allocation that might include multiple namespaces/jobs.

**Comment by rhc54** [comment]
Hmmm...indeed. Universe size is the number of allocated slots - which translates to the max number of processes allowed in a session outside of oversubscription. I'll clarify it.

Thanks for pointing it out!
