### ISSUE TITLE
Difference between PMIX_JOB_SIZE and PMIX_MAX_PROCS

### ISSUE THREAD

**Issue by krempel-pt** [pmix/pmix-standard#159]
Hello again,

this is another question on PMIx v3.0.

PMIX_JOB_SIZE is defined as
> Total number of processes in this job across all contained applications

and PMIX_MAX_PROCS as
> Maximum number of processes for this job.

What is the difference? As far as I understand it, a job is not meant to be dynamic in the number of its processes. It consists of one or more application, each having a spawn time defined number of processes which are all spawned together. So what is the meaning of PMIX_MAX_PROCS?

Thanks in advance.

**Comment by rhc54** [comment]
There are programming models that allow one to specify both a minimum number of processes to start, and a maximum number. This provides more flexibility for a scheduler that is resource constrained so a job can start earlier.

Note that there is no restriction that a job have a fixed number of processes - if a scheduler and a programming model supports adding/subtracting processes on the fly, then PMIx doesn't care. All we require is that the host environment generate an event alerting members of the job that the number of executing processes has changed.

It is true that MPI currently doesn't support that feature - but that is just one programming model.

**Comment by rhc54** [comment]
Updated text:
```
PMIX_JOB_SIZE "pmix.job.size" (uint32_t)
Total number of processes in this job across all contained applications. Note that this value
can be different from PMIX_MAX_PROCS . For example, users may choose to subdivide an
allocation (running several jobs in parallel within it), and dynamic programming models may
support adding and removing processes from a running job on-they-fly. In the latter case,
PMIx events must be used to notify processes within the job that the job size has changed.

PMIX_MAX_PROCS "pmix.max.size" (uint32_t)
Maximum number of processes that can be executed in this context (session, namespace,
application, or node). Typically, this is a constraint imposed by a scheduler or by user
settings in a hostfile or other resource description.
```

**Comment by krempel-pt** [comment]
Just a comment:
With the new description of PMIX_MAX_PROCS I would assume that used in session context it is equivalent to PMIX_UNIV_SIZE. Is it meant that way?

**Comment by rhc54** [comment]
Yes, that is correct. Some equivalencies are being preserved solely for historical reasons - people have used "universe size" for a long time.

**Comment by rhc54** [comment]
Just to close the loop here - this is the text on PMIX_UNIV_SIZE from the Standard:
```
Number of allocated slots in a session - each slot may or may not be occupied by an
executing process. Note that this attribute is the equivalent to the combination of
PMIX_SESSION_INFO_ARRAY with the PMIX_MAX_PROCS entry in the array - it is
included in the Standard for historical reasons.
```
