### ISSUE TITLE
pmix_server_fencenb_fn_t and PMIX_OPERATION_SUCCEEDED

### ISSUE THREAD

**Issue by krempel-pt** [pmix/pmix-standard#168]
Hello once again.

This is a question on PMIx v3.1.

In the reference implementation if PMIx_Fence is called for only processes on one node, the pmix_server_fencenb_fn is called by the server library, even if it could handle the whole fence by itself.

First Question: Is this intended behaviour and if so, why? Is there a case that I do not see right now that makes it necessary to inform the host server?

Second Question: If the host server sees, that only its own node is involved, it wants to return immediately with PMIX_OPERATION_SUCCEEDED. The standard allows that in general and says in that case the callback is not to be called. I wonder now if this is valid if data was provided to be collected by the fence. Of cause the server library has its own data already so it could work that way. Perhaps a concretion in the standard at this point would be meaningful, too.

**Comment by rhc54** [comment]
> First Question: Is this intended behaviour and if so, why? Is there a case that I do not see right now that makes it necessary to inform the host server?

It isn't required - just an optimization we didn't bother to implement. It would seem an unusual case that would require adding a check of both the nspace and rank values to the path, thus impacting all use-cases. Still, we could look at it some time.

> Second Question: If the host server sees, that only its own node is involved, it wants to return immediately with PMIX_OPERATION_SUCCEEDED. The standard allows that in general and says in that case the callback is not to be called. I wonder now if this is valid if data was provided to be collected by the fence. Of cause the server library has its own data already so it could work that way. Perhaps a concretion in the standard at this point would be meaningful, too.

You are correct - the data provided to the host has obviously already been collected by the PMIx server library. Thus, there is no need for it to be "returned" and the host is welcome to return "operation_succeeded". I can add some words to the standard to clarify that use-case.
