### ISSUE TITLE
PMIX_RANGE duplicate publish behavior unclear

### ISSUE THREAD

**Issue by dsolt** [pmix/pmix-standard#173]
The standard says, "Duplicate keys within the specified data range may lead to unexpected behavior depending on host RM implementation of the backing key-value store."    This implies to me that duplicate keys on different specified data ranges have a well behaved behavior.  I suggest we either change this statement to:   

"Duplicate keys may lead to unexpected behavior depending on host RM implementation of the backing key-value store." 

OR 

we need to clarify what happens if the same key is published at different levels.  Is there an implied hierarchy of ranges?   Some seem obvious, but others like PMIX_RANGE_NAMESPACE and PMIX_RANGE_LOCAL are not so obvious which one should be checked first and then PMIX_RANGE_CUSTOM of course messes everything up.

**Comment by rhc54** [comment]
Hmmm...the idea was that keys published on different ranges should be orthogonal to each other, but you make a good point - we/I had overlooked the fact that the ranges overlap. I think that trying to specify our way thru the labyrinth of precedence combinations is too onerous - I think your first proposal makes the most sense to me, though it leaves uncertainty. On the other hand, that might not be bad as it might discourage people from using duplicate keys!

**Comment by dsolt** [comment]
Yes, I don't see any good option here except to say that publishing keys at multiple ranges is undefined.

**Comment by rhc54** [comment]
I've been trying to clarify the standard based on this ticket plus the comments on #174 and it seems to me that the two are contradicting each other. If we require that the publish and lookup ranges exactly match, then we are saying that a key must only be unique within a specified range. Effectively, we are stating that the "range" defines a key-value store. Thus, something published into the ```PMIX_RANGE_LOCAL``` store cannot be accessed by a lookup searching the ```PMIX_RANGE_SESSION``` store.

On the other hand, if we say a key must be unique across all ranges (i.e., no duplicates published to different ranges), then we are saying there is a single "global/distributed" key-value store and the lookup should return a key if the search and publishing ranges intersect. In this case, one would have to question the value of having a ```range``` specification in both the publish and lookup APIs.

I believe, therefore, we should go with the first option - a key must be unique within the specified publishing range, and the lookup range must exactly match the published range. This uniqueness guarantee is easier for users to meet and it makes the search algo a little simpler.

Make sense?

**Comment by dsolt** [comment]
I've been thinking about this as well and I think that is the best way to go.   Each range is a very distinct and the publisher and lookup'er must agree on the range.
