### ISSUE TITLE
Publish default PMIX_RANGE is up to implementation but default unpublish is SESSION

### ISSUE THREAD

**Issue by dsolt** [pmix/pmix-standard#174]
Maybe this is a bit picky, but it is a little odd to me that the default range for publish is up to the implementation, but the unpublish range is PMIX_RANGE_SESSION by default.  This means that a code that calls PMIx_Publish(kvs, 1) and PMIx_Unpublish(keys,NULL,0) may see the Unpublish fail if the implementations default range for PUBLISH is not PMIX_RANGE_SESSION.

**Comment by dsolt** [comment]
So when I typed this in, I mistyped the args to publish, but in thinking about it, I wonder if PMIx_Publish should have been:

PMIx_Publish(info_to_publish, num_info_to_publish, info_to_influence_behavior, num_info_to_influence_behavior).   

Just a thought in case a group of people come along and decide to break backward compatibility and/or change API's dramatically. cough, cough

**Comment by rhc54** [comment]
> Maybe this is a bit picky, but it is a little odd to me that the default range for publish is up to the implementation, but the unpublish range is PMIX_RANGE_SESSION by default.

I'm not seeing that in v3.1 of the standard - it states the following on page 140:
```
Publish the data in the info array for subsequent lookup. By default, the
data will be published into the PMIX_SESSION range and with
PMIX_PERSIST_APP persistence.
```
Can you point me to where you see it being left to the implementation?

> PMIx_Publish(info_to_publish, num_info_to_publish, info_to_influence_behavior, num_info_to_influence_behavior).

Yeah, that's a good point...sigh.

**Comment by dsolt** [comment]
I don't know if I was looking at an old version, but I do now clearly see that Publish does say the default range is PMIX_RANGE_SESSION.   I'm not sure where I thought I saw a statement indicating that the implementation could determine this, but I re-read everything and it looks ok.   I think it is a bit confusing whether one process can publish something at the NODE level and another process does a lookup at the SESSION level or at an unspecified range and it should not find it.   I think that is true.. published and lookup data must 100% match on range specification.   I guess I'd like to see that more explicitly called out, but otherwise this actually looks good
