### ISSUE TITLE
Further separate out the PMIx client interface from the CL/host interactions

### ISSUE THREAD

**Issue by dsolt** [pmix/pmix-standard#175]
The PMIx standard defines a set of PMIx API's that are used to allow applications (clients) to communicate with a runtime environment.  However, interwoven within the presentation of that API is the concept of three distinct components:  a PMIx host server, a PMIx client library and a host RM (resource manager).  The distinction between the client library and a host server is  important because it would be of great benefit if an application could be linked against one implementation's PMIx client library and run on another system with a different implementation of the server.   However, the implementation of the host server and the distinction between a host PMIx server and a host RM component should have no impact on application developers (if it does, it leads to non-portable concepts that benefit only one implementation of PMIx).   Although the standard nicely attempts to separate out the API between the host server and host RM (See chapter 11 "Server-specific interfaces"), this architectural assumption can still be found spread through the document.   This issue is to explore the idea of further separating out these concepts, which would lead to at least the following benefits:

1) A application developer can more easily navigate the standard to understand how to use the PMIx APIs
2) Developers implementing the standard who wish to use the architecture of a separate host server + RM can easily find and understand what is required to implement that host PMIx server and understand what is required to implement the RM using a separate host PMIx server.
3) Developers implementing the standard who wish to directly implement the PMIx API can understand what is required without having to separate out text that is specific to the host server/host RM architecture.  
4) The separation will discourage concepts from being part of the PMIx API that are specific to  a host server/host RM architecture. 

To make this less nebulous, take a moment to look at a concrete example.

Standard 3.1, sections 3.4.17, 3.4.18 - These sections describe concepts that are completely irrelevant to an application developer (and may be very confusing for someone reading the document from that point of view), but they contain information that may be very important and should not simply be discarded.  The question I think we should ask is, 1) Is this information important between client and server.  If so, we should move it to a section that is clearly marked as important only for an implementer of the client or server.  If the information is important only host PMIx server and host RM, then that information should be moved to a section and clearly marked as important only for an implementer using the host server/host  RM architecture.   

I propose a thorough scouring of the document by a working group to look for all possible areas that could be sectioned off as relevant to  1)  client/server interactions 2) host PMIx server/host RM architecture implementations.

**Comment by rhc54** [comment]
Just to help clarify as people read thru the document. There was no intent here to specify a particular architecture. Instead, the document is framed in a way that matches how current RMs have historically dealt with PMI-like support - i.e., they have separated that support into a "plugin" (or equivalent) that handled all interactions with the client. The plugin then "passed" requests into the main RM code for processing.

This cleanly separated communication from request execution, and that was the intent of the work done on PMIx to-date. This separation, however, means that an interface must be defined by which requests are passed to the RM for processing and the results of that processing are returned for communication back to the requestor. This is what is captured in Chapter 11.

I can see that a "client" developer (whether of an app or a library) doesn't really care if who (the server or the RM) processes something, so splitting the "client" stuff out from everything else makes sense.

I do believe, however, that the "server" side needs to distinguish between the PMIx server (i.e., the portion that handles communications to/from the clients and tools) from the "host" (which may or may not be an RM process/daemon - e.g., we know that some file systems are working on PMIx integration). I have no issue with making clear that one doesn't have to make that separation - but I think we need to also make it easy for those who do split it out (e.g., use a 3rd-party's libpmix to handle the communication) as that has been the historical way of doing things.

So maybe we need to have the following sections:

- client-facing APIs. Remember that tools and "hosts" are also allowed to call these functions
- client/server messaging. This is where we can capture the cross-version requirements and document the wire protocol
- server-side interfaces. The equivalent of the server "function module" section in the current Chapter 11 - contains definition of what a PMIx library must provide to support embedding in a host environment
- host-side functional support. What a "host" is expected to do with incoming requests (whether directly captured by their own messaging code or passed via a server-side interface).

**Comment by garlick** [comment]
> Chapter 11 - contains definition of what a PMIx library must provide to support embedding in a host environment

This seems like a detail of the reference implementation, or is it really your intent that all implementations of PMIx be generically embeddable?  We were thinking of doing one just for Flux.

**Comment by rhc54** [comment]
The intent is to define a set of APIs that someone embedding a 3rd party library can expect to find, not to define what a use-specific implementation might do. Thus, if you are writing a "server" just for Flux, you can do whatever you want as it won't be used anywhere else - but if you are writing a 3rd party library for use by others (e.g., the reference implementation), then these are the APIs it needs to expose.

It's kinda like a message passing library. If you are writing something specific for your application, then you use whatever interfaces are most convenient for you. However, if you are writing a library for general use, it can be used more broadly if it exposes APIs consistent with the MPI standard.

The standard therefore applies to the general case - this is what a generically embeddable library must provide. It doesn't restrict what you do for a particular use-case as you aren't exposing that to others, and thus your internal interfaces don't have to follow the standard.

**Comment by dsolt** [comment]
> So maybe we need to have the following sections:
> 
>     * client-facing APIs. Remember that tools and "hosts" are also allowed to call these functions
> 
>     * client/server messaging. This is where we can capture the cross-version requirements and document the wire protocol
> 
>     * server-side interfaces. The equivalent of the server "function module" section in the current Chapter 11 - contains definition of what a PMIx library must provide to support embedding in a host environment
> 
>     * host-side functional support. What a "host" is expected to do with incoming requests (whether directly captured by their own messaging code or passed via a server-side interface).

I like that idea.

**Comment by gvallee** [comment]
@dsolt I like the suggestions and I wonder if it would it make sense to take that opportunity to clarify the terminology. For instance, clearly define what is a client, server and host? What do you think?

**Comment by jjhursey** [comment]
Notes from Teleconf April 26, 2019:
 * Question of how much of the PMIx Reference Implementation (PRI) details should be in the standard document vs a companion document to the PRI. A number of these notes may be useful in helping define the behavior of the interface or implementation choices - maybe isolate these into 'advice' regions (or a 'PRI advice' region).
 * Discussion about isolating the PMIx server interfaces from the RM behavior
   - Discussion of having a PMIx compliant implementation that doesn't provide the server API
   - Discussion of a wire protocol as an alternative to the server API
 * Three concepts mentioned - will work with the Slicing/Grouping working group here to define how to organize these concepts (maybe separate sections of the document or something).
   - Client-side API
   - Wire protocol between client and server
   - Server-side API
 * @dsolt will set up a teleconf to define the high-level objectives and work to do. Will email a doodle poll to the pmix-forum mailing list to gether interested folks.

**Comment by jjhursey** [comment]
Notes from Teleconf May 10, 2019:
 * Teleconf: Meeting May 14, 2019 at 9 am (Central) See mailing list for meeting information
 * Create issues for individual changes.

**Comment by jjhursey** [comment]
Ref Aug. 6 email with links to the current working document and repo:
 * https://groups.google.com/d/msg/pmix-forum/iDizaBpJ0uw/EDxECiLGFQAJ
   * https://github.com/dsolt/pmix-standard/tree/issue_175_chapter_1_organize_sections
   * https://github.com/dsolt/pmix-standard/pulls

**Comment by jjhursey** [comment]
This issue outlines the general charge of the Implementation Agnostic Working Group (IAWG). The IAWG has been progressing to the goals outlined here on a chapter-by-chapter basis.

Given the continued progress of the IAWG I don't think we need to keep this issue open any longer. Please reopen if there is a need to continue the discussion here instead of in the IAWG meetings.
