### ISSUE TITLE
Argv and other macros missing

### ISSUE THREAD

**Issue by rhc54** [pmix/pmix-standard#178]
Some of the macros were moved to an appendix that was subsequently commented out in the document. Should they be restored? Also seems that a few we defined in PRI and are commonly used are missing.

**Comment by jjhursey** [comment]
Per teleconf:
 * Bring back the `App_Support.tex` appendix
 * List them as optional with enough of a description so that if a PMIx library does not provide them (or they are dropped at some point) a user could re-create the macro.
