### ISSUE TITLE
Creating PMIx "classes/slices" based on functionality

### ISSUE THREAD

**Issue by SteVwonder** [pmix/pmix-standard#182]
### Main Idea

- Formally specify the "functionality" of PMIx function/attributes
- Functionality being things like: boostrapping, tools, fault-tolerance (terms TBD)

### Motivation

The main motivation for the "functionality classes" is for ease of reference when discussing PMIx as a developer, user, and procurement-writer.  It would be great to be able to say something akin to "our implementation supports all of the *bootstrapping* and *tools* interfaces from version 5.2".

The functionality classes could be combined with the stability classes proposed in #179 to be even more precise, e.g., "we require all of the *stable* *bootstrapping* interfaces and the *experimental* *fault-tolerance* interfaces."

As a longer-term motivation, I could see this being useful for handling portability across implementations.  For example, it may be useful to have an API for querying what "functionality classes" a particular implementation supports, as an alternative to querying the availability of each individual function or key (#6). (Note: @rhc54 mentioned in a [different thread](https://github.com/pmix/pmix-standard/issues/179#issuecomment-480309699) that this functionality could be built on top of existing query capabilities). It could also simplify things for users.  Rather than having to reason about and program their applications for the potential (un-)availability of each individual function/key, they could instead program for the (un-)availability of the more coarse-grained classes.

### Things to Discuss

- What slices/classes should we group the various attributes/functions into?
  - Bootstrapping, tools, fault-tolerance, etc?
- What process should we use for labelling new/existing interfaces?
- Is there relevant prior art that we should consider?

**Comment by jjhursey** [comment]
Notes from Teleconf May 10, 2019:
 * Doodle poll (see the mailing list) to find a time to have a kick-off meeting on this topic.

**Comment by SteVwonder** [comment]
Notes on the various use-cases and the WG phone calls can be found in this google drive folder: https://drive.google.com/open?id=1Cuum5Rx81gG4iMNPz7SvEsM244KfeEH_

**Comment by jjhursey** [comment]
@SteVwonder That link does not seem to work for me - returns a 404.

**Comment by SteVwonder** [comment]
Thanks @jjhursey for catching that.  Github was "helpfully" dropping the `_` off the end of the link.  Updated the comment with a manual link that seems to work now.

**Comment by jjhursey** [comment]
The PMIx v5.0 (draft) standard includes **Appendix B: Use-Cases** which currently houses the following use cases:
 * Business Card Exchange #191
 * Debugging #216 and #239
 * Hybrid Applications #232
 * MPI Sessions #260
 * Cross-Version Compatibility #357

Other use cases will be added as the standard progresses.
