### ISSUE TITLE
Clarify intent of cbdata in function signatures

### ISSUE THREAD

**Issue by jjhursey** [pmix/pmix-standard#184]
In a discussion earlier today it was pointed out that the PMIx standard is unclear on the intent of the `cbdata` option to many of the nonblocking interfaces. This should be clarified in the standard.

Below is a rough explanation that probably needs more polish:

> Many PMIx interfaces, particularly nonblocking interfaces, use a `void* cbdata` object passed to the function that is then passed to the associated callback. In a client-side API, the `cbdata` is a client-provided context (opaque object) that the client can pass to the nonblocking call (e.g., `PMIx_Get_nb`). When the nonblocking call (e.g., `pmix_value_cbfunc_t`) completes the `cbdata` is passed back to the client _without modification_ to allow the client to associate a context with that callback. This is useful if there are many outstanding nonblocking calls. The additional arguments to the callback function convey any additional information (e.g., `kv`) requested in that operation. 
>
> A similar model is used on the server-side API, though slightly inverted as the PMIx library is often the one providing the `cbfunc` and `cbdata` to be used when the requested operation (e.g., fence) is complete. The PMIx library is making an upcall into the RM via the PMIx server-side API with a specific `cbfunc` and `cbdata`. The PMIx library expects the server to call the `cbfunc` with the necessary arguments and pass back the original `cbdata`. This gives the server-side PMIx library the ability to associate a context with the call back (since multiple operations may be outstanding). The `cbdata` that the server sees is most likely not the same as what the client put into their side of the interface, but likely context specific to the PMIx implementation.

**Comment by rhc54** [comment]
> The cbdata that the server sees is most likely not the same as what the client put into their side of the interface, but likely context specific to the PMIx implementation.

I think that it is more than likely - it is pretty much guaranteed, isn't it, as the client and server are executing in two completely different processes? Even if the client library passed the pointer address to the server, the value would be meaningless as it refers to an address in the client's context.

Might also be worth providing the usual caution about ensuring the address being passed remains valid throughout the return call - e.g., don't pass the address of a local variable in a function, return from that function, and then attempt to use that address in a subsequent callback function.

**Comment by rountree** [comment]
@rhc54 The current issue I'm working on might be the exception that proves the rule, but I do indeed have a client and server within the same address space.  

I believe all of the callback function signatures return `void`.  What should the error procedure be if `cbdata` is unrecognized?

**Comment by jjhursey** [comment]
> > The cbdata that the server sees is most likely not the same as what the client put into their side of the interface, but likely context specific to the PMIx implementation.
> 
> I think that it is more than likely - it is pretty much guaranteed, isn't it, as the client and server are executing in two completely different processes? Even if the client library passed the pointer address to the server, the value would be meaningless as it refers to an address in the client's context.

I might strike that line from my original post. Since the recipient of the `cbdata` (either client-side API in the PRI or the RM from an upcall) shouldn't be messing with it, it doesn't really matter where it came from. I've seen implementations pass a memory address across server boundaries with the understanding that when it comes back that it will only be used by the process that originated it. It's a somewhat similar notion here.

> 
> Might also be worth providing the usual caution about ensuring the address being passed remains valid throughout the return call - e.g., don't pass the address of a local variable in a function, return from that function, and then attempt to use that address in a subsequent callback function.

This would be good to add. Whoever passes in the `cbdata` must ensure that it remains valid until the associated callback is called.

---

> I believe all of the callback function signatures return void. What should the error procedure be if cbdata is unrecognized? (Which is to say, should the standards concern itself with specifying an error procedure?)

All of the callback functions (that I know of) do return `void`. I'm not sure what the PMIx library would do if it received a non-success return code from a callback. Since there is nowhere to return that value it would be dropped. The PMIx could raise an error/event, but it would have to be somewhat generic.

If the callback encountered an error they can make additional PMIx calls in the callback function (unless otherwise restricted). So the callback could call `PMIx_Abort` if it is that critical or call `PMIx_Notify_event` if they want to raise a specific event. In the latter case, they can `PMIx_Register_event_handler` an error handler callback (`pmix_notification_fn_t`) before the call that is triggered when that event is raised. That also gives other libraries listening for the same event a chance to take action.

**Comment by rhc54** [comment]
> @rhc54 The current issue I'm working on might be the exception that proves the rule, but I do indeed have a client and server within the same address space.

Let me clarify a bit. Servers are allowed to call any client function, so in that sense they are both client and server. If the server library wants to do something that flows up to the host, then the cbdata belongs to the server library - there is no separate "client" in that sense.

> 
> I believe all of the callback function signatures return `void`. What should the error procedure be if `cbdata` is unrecognized? (Which is to say, should the standards concern itself with specifying an error procedure?)

As @jjhursey indicated, the only option is to raise an event. I suppose we could try to define some kind of "standard" event code to use for each callback function and ask that they provide info structs for further explanation. Alternatively, we could follow current practice where the implementor of that callback generates whatever event best describes the problem - if desired, we could ask that they include the location of the issue (e.g., what function) in the info structs.

**Comment by jjhursey** [comment]
PR #214 has a nice clarification on this.
