### ISSUE TITLE
Many attributes presented in request-related attributes sectiion have no clear use

### ISSUE THREAD

**Issue by dsolt** [pmix/pmix-standard#185]
I see several attributes such as:

PMIX_NOTIFY_COMPLETION 
PMIX_JOB_TERM_STATUS 
PMIX_ANL_MAP
(and I believe many more)

These are presented in a very generic way, but no PMIx routine is given that accepts these as required or optional.   If the goal it to reserve these for some internal use or some other non-documented purpose, then we should note that somewhere.  As it is now, they are just kind of "there" with no real explanation of how they would get used.

**Comment by rhc54** [comment]
I'll update the doc and try to capture these. Some of them relate to tools which will be covered in the upcoming chapter. All are actually used in user interactions, not internally.

**Comment by rhc54** [comment]
@jjhursey Perhaps it would be possible to provide a report that shows attributes that are not cited by any API? All the attributes are actually used somewhere - it could be that people just aren't seeing the reference (most likely reason) or that the reference is missing, or it is coming in a future chapter. Without seeing which ones are not referenced, it becomes almost impossible to chase them down.

**Comment by jjhursey** [comment]
Yeah, I think that should be possible. It'll require a bit of LaTeX hackery to get right. I'll put it on my to do list and try to tackle it this weekend.

**Comment by rhc54** [comment]
@jjhursey Let me know if you get a chance to do this.

**Comment by jjhursey** [comment]
@rhc54 I posted a script to do the attribute check (and it's current output) in PR #223. Let me know what you think.

**Comment by jjhursey** [comment]
We added a check script (ran at the bottom of 'make') that makes sure that for every attribute declared it is connected to some usage in the text. I think going beyond just a reference is a topic for the Slices/Grouping functionality working group - meaning make a proper use case for each one.

```
make check-attr-ref
====> Checking for Attributes Declared, but not referenced
  0 of 462 Attributes are missing reference
```
