### ISSUE TITLE
PMIX_JOB_CTRL_ID  has no clear use

### ISSUE THREAD

**Issue by dsolt** [pmix/pmix-standard#186]
A host is required to accept this , but the only description is "Provide a string identifier for this request."   What is a host expected to do with it?

**Comment by rhc54** [comment]
There was more verbage in the original RFC, IIRC, but fundamentally the notion is that the user can provide an identifier for the requested operation, thus allowing them to later request status of the operation or to terminate it. The host, therefore, is supposed to track it with the request for future reference. I'll update the doc accordingly.
