### ISSUE TITLE
Definition of `PMIX_GROUP_ASSIGN_CONTEXT_ID`

### ISSUE THREAD

**Issue by SteVwonder** [pmix/pmix-standard#194]
`PMIX_GROUP_ASSIGN_CONTEXT_ID` and `PMIX_GROUP_NOTIFY_TERMINATION` are both defined to be "Notify remaining members when another member terminates without first leaving the group. The default is false".  I assume this definition is correct for the latter and the former got the definition through copy/paste.

I'm not sure what is the intended definition of `PMIX_GROUP_ASSIGN_CONTEXT_ID`.  There isn't any text that I am able to find in the standard or RFCs that describes this attribute or the (presumably related) `PMIX_GROUP_CONTEXT_ID` attribute.

### References

This primarily applies to Chapter 3 (where the attribute is defined), but it affects Chapter 12 as well (where the attribute is referenced).

**Comment by rhc54** [comment]
Please see #197 for clarification. The primary use-case was for the MPI Session folks as a means of creating a globally unique communicator ID at time of group construct, thus avoiding another operation to compute one. However, there is nothing in PMIx that constrains the context ID to that usage.
