### ISSUE TITLE
Clarification on `PMIX_GROUP_FT_COLLECTIVE`

### ISSUE THREAD

**Issue by SteVwonder** [pmix/pmix-standard#195]
`PMIX_GROUP_FT_COLLECTIVE` is defined in Chapter 3 to mean "Adjust internal tracking for terminated processes. Default is false"

The only reference to `PMIX_GROUP_FT_COLLECTIVE` that I can find is under `PMIx_Group_leave` in Chapter 12.  The text there states: "All PMIx-based collectives such as `PMIx_Fence` in action across the group will automatically be adjusted if the collective was called with the `PMIX_GROUP_FT_COLLECTIVE` attribute (default is false) – otherwise, the standard error return behavior for that collective will be executed."

### Suggested Clarification

Do any of the collectives currently support this attribute? If so, I think it would be useful to include `PMIX_GROUP_FT_COLLECTIVE` in the `Format` sections of the relevant collectives.  If none of them support it, it may make sense to remove it from the standard until one does.

### References

Chapter 3 (attribute definition) and Chapter 12 (attribute reference).

**Comment by rhc54** [comment]
Only the `fence` API currently was expected to support it, but I'm okay with just removing it for now. The FT folks can add it back if/when they are ready to actively support FT collectives in PMIx.
