### ISSUE TITLE
Clarify example text around key/value management regarding PMIX_NUM_NODES

### ISSUE THREAD

**Issue by dsolt** [pmix/pmix-standard#208]
Chapter 5 Line 7:

> Keys are required to be unique within a specific level of informarion as defined in 3.4.11. For example, a value for PMIX_NUM_NODES can be specified for each of the session , job , and application levels. However, subsequently specifying another value for that attribute in the session level will overwrite the prior value.

Besides the typo (informarion), This may be a bad example since the user is not allowed to change PMIX_NUM_NODES based on this advice to users on the next page:

Note that keys starting with a string of “pmix” are exclusively reserved for the PMIx standard and must not be used in calls to PMIx_Put . Thus, applications should never use a defined “PMIX_” attribute as the key in a call to PMIx_Put .

This leads to confusion as to what the text around PMIX_NUM_NODES is trying to communicate.   I think the example is trying to explain that the resource manager could 
change the value of PMIX_NUM_NODES at the session level when a new job was added, for example.   If that is the case, then I propose we use the text below, however I also would note that I don't believe the PMIx reference implementation has any way to do this currently which either makes this a poor example or calls for changes in the PRI.   (How would a server using the PMIx reference implementation update PMIX_NUM_NODES as the session level? ).   

### Suggested Clarification

Keys are required to be unique within a specific level of information as defined in 3.4.11. For example, a value for PMIX_NUM_NODES can be established by the PMIx server for each of the session, job , and application levels.  If new nodes were introduced to a session through a  PMIx_Spawn call, the server could change the value in the session level which would change the value at the session level for all clients running inside that session.   

### References

Chapter 5 line 7.

**Comment by rhc54** [comment]
Yeah, it is a bad example - but perhaps not for the reason you cite. The problem is that the example refers to information the server provides and isn't something the user can ever specify. The session, job, and app level arrays (as described in the referenced sections) all deal with information being passed from the host to the PMIx server library - this is the only place where the confusion over meaning is resolved using those arrays.

The best solution is probably just to remove that paragraph as we already addressed the multi-level key duplication issue in the referenced section. No need to revisit it here.

**Comment by dsolt** [comment]
Yes, agreed.   As it stands now, that example does not set the user up well for the next section on PMIx_Put.  After reading the introduction the reader might expect the PMIx_Put to include a scope of session, job and app, but instead includes a scope of local, remote, global, etc.    I would either get rid of the whole paragraph or else fully explain all the details of server provided vs user provided data and the differences in their scopes at this point.
