### ISSUE TITLE
Reference to pmix.org website in `PMIx_Get` Description

### ISSUE THREAD

**Issue by SteVwonder** [pmix/pmix-standard#231]
In the "Advice to Users" section of the `PMIx_Get` description, there is the following sentence:
> The list of data referenced in this way is maintained on the PMIx web site at https://pmix.org/support/faq/wildcard-rank-access/ but includes items such as the number of processes in the namespace ( PMIX_JOB_SIZE ), total available slots in the allocation ( PMIX_UNIV_SIZE ), and the number of nodes in the allocation (PMIX_NUM_NODES ).

When you visit that link, it contains only this sentence:
> Information accessed via calls to PMIx_Get or PMIx_Get_nb require specification of both the nspace and rank of the publishing process.

I do not think the content on the current version of that webpage adds much to the description of the interface. In addition, this redirect to the website prevents the standard from being self-contained.

### Suggested Clarification

I am suggesting to remove the url from the standards document and instead enumerate the pieces of data accessed in this way directly within the standard.  Unless of course that is an implementation detail; if so, we should brainstorm on the best way to handle that.

### References

Chapter 5, Page 129, Line 17 of the current master (ba66b70f038fc8a08d36c009bec0caa3b2d16516)

**Comment by jjhursey** [comment]
This was fixed in PR #253 and is included in the upcoming v5.0 release and in v4.1 release.
