### ISSUE TITLE
PMIX_NPROC_OFFSET not well defined 

### ISSUE THREAD

**Issue by dsolt** [pmix/pmix-standard#236]
**Describe your question or clarification request here**

Unclear what this means:

PMIX_NPROC_OFFSET "pmix.offset" (pmix_rank_t)
Starting global rank of this job - referenced using PMIX_RANK_WILDCARD .

starting?  global?   - neither of these are well defined.   

### Suggested Clarification

I don't have a suggestion because its not clear how this is used.   I know PAMI uses this, but trying to  debug it, I can't tell what they are doing with it or how they expect it to be set.   I somehow expect that "global" in this definition really is meant to be "for rank 0 of this app, which rank is this in the total set of all process ever created by this PMIx server".   This way when PAMI does a connect/accept to another set of ranks, it can store them all in a contiguous array with unique starting point for each.  I'm not 100% sure of that, but if it is the case I don't see how this can be a good design.  If I start an app FOO, then I run 1 billion other 1-rank jobs and then I start an app BAR and foo and bar connect/accept to each other, should PMIX_NPROC_OFFSET of BAR be 1 billion?   I think  PMIX_NPROC_OFFSET is not well defined and my fear is that once it is well defined we will see it is not practical/useful.

**Comment by rhc54** [comment]
We can add clarification to it. It isn't as "global" as you are thinking for the very reason you cite. At least in PRRTE, it is used as follows:
```c
    /* set the offset so shared memory components can potentially
     * connect to any spawned jobs
     */
    jdata->offset = prrte_total_procs;
    /* track the total number of procs launched by us */
    prrte_total_procs += jdata->num_procs;

```
In other words, it tracks the number of procs launched by that particular PRRTE instance (as an example), which for PRRTE means within the current allocation. We don't store ranks in the manner you describe for PAMI for the very reason you cite - it explodes arrays.

IIRC, OMPI's shared memory module uses the value as per the description, but that might be an old understanding. I know we recently enabled shared memory operations between comm-spawned jobs, but I forget what was required to make it work.

Quite possible that we don't need it any more. Should at least check the ompi/vader code first.

**Comment by dsolt** [comment]
I think PAMI is still using this... I'm asking some PAMI folks to jump on this discussion.   You say, " it tracks the number of procs launched by that particular PRRTE instance ".   I'm not sure how that limits the values from exploding as in my example.  Here is an example:

I get an allocation and run multiple job steps:

example 1:

% jsrun --np 1 myapp1
1:0 MY value of PMIX_NPROC_OFFSET=0
% jsrun --np 1 myapp2 
2:0 MY value of PMIX_NPROC_OFFSET=?? 

example 2:

jsrun --np 2 jsrun --np 1 myapp1
4:0 MY value of PMIX_NPROC_OFFSET=??
5:0 MY value of PMIX_NPROC_OFFSET=??

I'm not sure what ?? should be in all of these cases.  If it increments in example 1, then it seems like you could end up with a crazy value for PMIX_NPROC_OFFSET.  If it only increments in example 2 (but not 1), then it seems like myapp1 and myapp2 could not connect/accept to each other using PAMI in example 1.   Either way I feel like PAMI should move away from this strange method of coordinating ranks.

**Comment by dsolt** [comment]
A third example would be:

jsrun --np 1 myspawn_app (where myspawn_app calls PMIx_Spawn of 1)
6:0 MY value of PMIX_NPROC_OFFSET=??
7:0 MY value of PMIX_NPROC_OFFSET=??

I'm guessing this is the actual case where PMIX_NPROC_OFFSET was intended to work and be incremented.  If that is the case, then PAMI needs to be aware that connect/accept isn't going to work with job steps that were not created by one another.

**Comment by rhc54** [comment]
Yes, the value can grow quite large if you have, for example, a persistent daemon launching millions of jobs. That wasn't the scenario it was originally used for - we were more concerned with the case of a daemon only existing for the life of an allocation (our session) and where someone might run a large, but constrained, number of jobs.

PRRTE stores ranks based on their job rank, with each job having its own structure. Jobs are stored in a hash table to avoid the problem of a jobid blowing out an array. So we would never see the problem of someone storing a rank on some "global" array based on their job rank + offset. Besides, when job steps end, you'll want to cleanup their storage - easier to do that if the job is a standalone object.

Anyway, is this an issue where you need to understand "offset"? Or is this an issue of PAMI's storage architecture?

**Comment by dsolt** [comment]
I think I just need to know in which of the above 3 examples does PMIX_NPROC_OFFSET needs to change.

**Comment by dsolt** [comment]
I think based on @rhc54 comments, that i only need to increment it for example #3 and PAMI probably can't connect/accept ranks in any other case.

**Comment by rhc54** [comment]
Seems like a reasonable interpretation to me. I'll have to check PRRTE to see what it does.

**Comment by jjhursey** [comment]
We have these two attributes which seem connected:
```
PMIX_GLOBAL_RANK "pmix.grank" (pmix_rank_t)
  Process rank spanning across all jobs in this session.
PMIX_NPROC_OFFSET "pmix.offset" (pmix_rank_t)
  Starting global rank of this job - referenced using PMIX_RANK_WILDCARD .
```

So `PMIX_GLOBAL_RANK` is session wide rank, and could be used to aid connect/accept as a unique identifier. The `PMIX_NPROC_OFFSET` (I agree it needs clarification) seems to be the first/lowest `PMIX_GLOBAL_RANK` within the job.

Is that a correct interpretation?

**Comment by rhc54** [comment]
Yes, that is correct

**Comment by rhc54** [comment]
I suppose in some ways ```PMIX_NPROC_OFFSET``` is redundant as you could simply get the ```PMIX_GLOBAL_RANK``` of ```rank=0``` in your job. I'm not married to having that key if folks find it confusing and/or unnecessary.

**Comment by jjhursey** [comment]
More precisely:
```
PMIX_NPROC_OFFSET of rank PMIX_RANK_WILDCARD in namespace X is the same as
PMIX_GLOBAL_RANK of rank 0 in namespace X.
```

**Comment by dsolt** [comment]
Ok, I'm going to close this, but in our WG edits to chapter 6, I'm going to propose changing PMIX_NPROC_OFFSET description to "Starting global rank of the specified job.   The value returned is the same as PMIX_GLOBAL_RANK of rank 0 for the specified job."
