### ISSUE TITLE
What happens if a host calls PMIx_Notify_event with non-local ranks 

### ISSUE THREAD

**Issue by dsolt** [pmix/pmix-standard#238]
The text for PMIx_Notify_event says:

> The PMIx server calls this API to report events it detected itself so that the host SMS daemon [can?] distribute and handle them, and to pass events given to it by its host down to any attached client processes for processing.   

I am trying to understand how to use this function inside the RM (host in the above text?).   It is immediately confusing because it describes how the PMIx server uses this call (internally?) unless the meaning of "Pmix server" is not what I'm thinking it is.  I'm assuming it is the pmix server that is part of the pmix library.   I'm not sure what the value of this sentence is but I think I'm missing it.    

I am trying to understand what happens if my RM code calls this API.  If the range includes non-local ranks, will the non-local ranks be ignored, or will this result in calls back into the RM through the pmix_server_notify_event_fn_t callback.    I'm concerned if there will be an infinite loop if my RM code has the pmix_server_notify_event_fn_t callback called and then I call PMIx_Notify_event on every node with the range of processes on each node on all nodes.  If the API isn't handled differently when called by a client vs called by the RM, then it seems like it would result in an infinite loop.   If it is handled differently, then this should be called out in the description 

I hope this makes sense... simple example:

client calls PMIx_Notify_event() with a custom range (PMIX_RANGE_CUSTOM) of namespaces 1 and 2.  PMix library I assume will then call pmix_server_notify_event_fn_t to get this message out to all the hosts where namespaces 1 & 2 are running.   RM does so and calls PMIx_Notify_event() on each host where namespaces 1 & 2 are running.  The question is, does the RM need to make sure to only pass in a custom range that only includes local ranks?  If the server calls PMix_Notify_event on a node where only processes from namespace 1 are running, will the pmix library/server just notify the ranks it can and be done or will it notify the ones it knows about and then make a call to pmix_server_notify_event_fn_t callback to let the RM know to notify the processes it doesn't know about?   

I can obviously get the answer to this experimentally or by looking through OpenPMix code, but I wonder if this needs to be clearer in the document?

### Suggested Clarification

I can suggest a change once I understand how it is intended to work.

### References

11.2.1 - pmix_server_notify_event_fn_t
8.1.3 - main issue

**Comment by rhc54** [comment]
> The question is, does the RM need to make sure to only pass in a custom range that only includes local ranks? If the server calls PMix_Notify_event on a node where only processes from namespace 1 are running, will the pmix library/server just notify the ranks it can and be done or will it notify the ones it knows about and then make a call to pmix_server_notify_event_fn_t callback to let the RM know to notify the processes it doesn't know about?

The RM currently needs to protect itself against the infinite loop problem. The PMIx server library will _always_ return an event notification to the RM as it cannot know if the targeted processes are going to appear at some later time. Thus, it takes the conservative approach of always notifying the RM.

We could resolve this in the library itself by having the Standard require that notifications delivered to the PMIx server library by the RM not be echoed back to the RM. We would just need to track in the library that "this event came from the RM" so we don't upcall it again. I'd be okay with that change.

In the meantime, our RTE simply adds an attribute marking that "we delivered this to the PMIx server library". When we get an upcall from the PMIx server library, we check for that attribute and ignore the upcall if found. In retrospect, we should probably move that to the PMIx server library and reduce the burden on the RM.

Remember, it is the responsibility of the RM to deliver that event to all PMIx server libraries where the targeted procs either are currently running, or (if they haven't started yet) might be running at some point in the future as the events are required to be cached by the PMIx server library.

**Comment by dsolt** [comment]
Ok, this makes sense.  I can think of some possible short clarifying texts that could be added to the standard to make this clearer.  I can make a note of that on my own if you want to close this.  With the work I'm involved in in chapter 5, it may be a while till I get to this, so feel free to leave it open or close it, but I'll plan to add some text someday.

**Comment by rhc54** [comment]
Modified the `PMIx_Notify_event` language:
```text
Host SMS daemons call the API to pass events down to its embedded PMIx server both for
transmittal to local client processes and for the host’s own internal processing where the
host has registered its own event handlers. The PMIx server library is not allowed to echo
any event given to it by its host via this API back to the host through the
pmix_server_notify_event_fn_t server module function. The host is required to deliver the
event to all PMIx servers where the targeted processes either are currently running, or (if
they haven’t started yet) might be running at some point in the future as the events are 
equired to be cached by the PMIx server library.
```
and correspondingly in the `pmix_server_notify_event_fn_t` section:
```text
Note that the \ac{PMIx} server library is not allowed to echo any event given to it by its
host via the \refapi{PMIx_Notify_event} \ac{API} back to the host through the
\refapi{pmix_server_notify_event_fn_t} server module function.
```
