### ISSUE TITLE
Event Handler Registration + Programming Model Declaration Questions

### ISSUE THREAD

**Issue by SteVwonder** [pmix/pmix-standard#240]
While working on the hybrid programming model use-case (#232), I had a few questions about the event handler registration (i.e. `PMIx_Register_event_handler`) and the programming model declarations that can be passed to `PMIx_Init`.

1. Is it possible to pass user data to the `pmix_notification_fn_t evhdlr`?  The `cbdata` in the `PMIx_Register_event_handler` signature appears to be associated with the `pmix_evhdlr_reg_cbfunc_t cbfunc`. Quoting from the standard: `cbdata: Data to be passed to the cbfunc callback function (memory reference)`. If it is possible to pass user data, how is the data passed through (is `cbdata` passed to both callbacks?) and how is the data accessed from within the notification callback?  Is it accessed via the `cbdata` that is associated with the `pmix_event_notification_cbfunc_fn_t cbfunc`?
2. If a process declares its programming model when calling `PMIx_Init` and then registers an event handler for `PMIX_MODEL_DECLARED`, does this hypothetical process's notification callback get called for it's own model declaration event?  Is the answer implementation-specific based on caching?
3. If multiple models were declared before our hypothetical process registered a handler, are all of the model declaration events "played back" to the notification callback one-by-one?  If this question makes no sense across separate processes, then `sed s/process/thread/g`.
4. What does the format of the `PMIx_Init`-based events look like?  Are the relevant contents of the `pmix_info_t` passed to `PMIx_Init` copied and passed along to the `pmix_notification_fn_t` notification callback via the `info` argument?

### References

While writing this issue, I was referencing: `PMIx Standard – Version 4.0 (Draft) – Created on March 11, 2020`:

- Chapter 8.1 (event notification)
- Chapter 3.5.10 (notification function)
- Chapter 4.2.1 (pmix_init)

Thanks!

**Comment by rhc54** [comment]
> Is it possible to pass user data to the pmix_notification_fn_t evhdlr? The cbdata in the PMIx_Register_event_handler signature appears to be associated with the pmix_evhdlr_reg_cbfunc_t cbfunc. Quoting from the standard: cbdata: Data to be passed to the cbfunc callback function (memory reference).

Yes, you can pass user data in the registration call that will be returned to you in the event handler when invoked:
```text
#define PMIX_EVENT_RETURN_OBJECT            "pmix.evobject"         // (void*) object to be returned whenever the registered cbfunc is invoked
                                                                    //     NOTE: the object will _only_ be returned to the process that
                                                                    //           registered it
```
The registration cbdata only comes back in the `pmix_evhdlr_reg_cbfunc_t` function and is intended to support the registration operation itself. Any object specified by `PMIX_EVENT_RETURN_OBJECT` is not included in the registration callback - it is solely returned in the event handler callback.

> If it is possible to pass user data, how is the data passed through (is cbdata passed to both callbacks?) and how is the data accessed from within the notification callback? Is it accessed via the cbdata that is associated with the pmix_event_notification_cbfunc_fn_t cbfunc

The user-provided object is returned in the `pmix_info_t` array of the `pmix_notification_fn_t` handler - you can retrieve it by searching for the `PMIX_EVENT_RETURN_OBJECT` attribute

**Comment by rhc54** [comment]
> If a process declares its programming model when calling PMIx_Init and then registers an event handler for PMIX_MODEL_DECLARED, does this hypothetical process's notification callback get called for it's own model declaration event? Is the answer implementation-specific based on caching?

Yes - you do get a callback for your own declaration. It would be rather difficult to avoid it as PMIx doesn't know who (i.e., which programming model library) is registering for the event. Easy enough for the individual libraries to check for their own model and ignore it.

**Comment by rhc54** [comment]
> If multiple models were declared before our hypothetical process registered a handler, are all of the model declaration events "played back" to the notification callback one-by-one? If this question makes no sense across separate processes, then sed s/process/thread/g.

Yes, each registered handler would get a complete "playback" of the model invocations, and they would indeed be provided one-by-one (in the case of OpenPMIx, it is in the order of declaration).

Model declarations are delivered solely within a process - they aren't communicated across processes.

**Comment by rhc54** [comment]
> What does the format of the PMIx_Init-based events look like? Are the relevant contents of the pmix_info_t passed to PMIx_Init copied and passed along to the pmix_notification_fn_t notification callback via the info argument?

PMIx caches the provided `pmix_info_t` values as part of the event. When someone registers for the model declaration event, we then pass those values to the specified handler. We retain the cache in case additional handlers are eventually registered. There is no requirement that the declarer retain those `pmix_info_t` values that they provided to `PMIx_Init` once returning from that routine.

Note, however, that we don't multiply notify a given handler. In other words, consider the case where you register a handler and get a callback notifying you of model A. At some later time, another model (say B) declares itself. Your handler will get a callback notifying you of model B, but the callback will not also include model A as this handler was already notified of it.

**Comment by SteVwonder** [comment]
Thanks @rhc54!  That was what I needed to get the example written. Closing :)
