### ISSUE TITLE
PRI or PRL?

### ISSUE THREAD

**Issue by rhc54** [pmix/pmix-standard#25]
We seem to keep switching between PMIx Reference Implementation and PMIx Reference Library throughout the standards document. Should we be more consistent and just one or the other of these?

**Comment by jjhursey** [comment]
Decided to match whatever we used in the published work. I'll look up, and file a PR to make it consistent. We _think_ it's `PMIx Reference Implementation`

**Comment by jjhursey** [comment]
Reviewing the journal paper we have 1 reference to the `PMIx Reference Library`, but many more references to the `PMIx Reference Implementation`. So we should go with the latter. I'll make that change in my pass through the document (associated with PR #37)

**Comment by jjhursey** [comment]
There are a few places where we talk about the `PMIx library` somewhat as a separate concept from the PRI. I left some of those in place as they were talking generally about the library associated with, for example, the server or client. Or where replacing it make it sound odd. We can go through and fix those up if needed. But the first pass is complete in PR #37

**Comment by rhc54** [comment]
This now looks good to me.
