### ISSUE TITLE
Section "Destruct the pmix_proc_t structure" not including macro definition

### ISSUE THREAD

**Issue by cniethammer** [pmix/pmix-standard#251]
Section "Destruct the `pmix_proc_t` structure" states

> However, the macro is provided for symmetry in the code and for future-proofing should some allocated field be included some day.

but the section misses the name and argument specification for the mentioned macro.

In the tex source of the standard [`\declaremacro{PMIX_PROC_DESTRUCT}`](https://github.com/pmix/pmix-standard/blob/e88af9e84cfdffaf81b40acd92f96c51598e3630/Chap_API_Struct.tex#L736) is used
and this name is also implemented as a macro with no side effect in the PRI since 2015.

### Suggested Clarification
Addition of macro part
```
\cspecificstart
\begin{codepar}
PMIX_PROC_DESTRUCT(m)
\end{codepar}
\cspecificend

\begin{arglist}
\argin{m}{Pointer to the structure to be destructed (pointer to \refstruct{pmix_proc_t})}
\end{arglist}
```

### References
* [3.2.5.2 Destruct the pmix_proc_t structure](https://github.com/pmix/pmix-standard/blob/e88af9e84cfdffaf81b40acd92f96c51598e3630/Chap_API_Struct.tex#L736)
* [Implementation of PMIX_PROC_DESTRUCT in openpmix](https://github.com/openpmix/openpmix/blob/ea1aee880ae5df3f3b6794693557e62950e5e0c0/include/pmix_common.h.in#L1590)

**Comment by rhc54** [comment]
Fixed this in #252
