### ISSUE TITLE
What to do with items deprecated in v3?

### ISSUE THREAD

**Issue by rhc54** [pmix/pmix-standard#259]
There are a number of items that were deprecated in v3. As we work on completing v4, what shall we do with those items? Per the rules, they can (perhaps should?) be removed. However, this breaks backward compatibility, and so libraries will be forced to retain them until at least their earlier versions fall out of support.

However, if we retain them and continue to show them as "deprecated", then what does "deprecated" mean?

Not sure of the best answer here. I'm okay if folks want to wait for v5 to deal with this problem.

**Comment by jjhursey** [comment]
Per PMIx developer teleconf Aug. 6, 2020:
 * Leaning towards removing them.
 * Would like a list of the attributes impacted.

**Comment by jjhursey** [comment]
See (new) Chapter 2 (Revision History) in https://github.com/pmix/pmix-standard/pull/267 for the list of deprecated items.
