### ISSUE TITLE
Final prep for v4 release

### ISSUE THREAD

**Issue by rhc54** [pmix/pmix-standard#266]
Ralph edits - will check off each chapter once complete and ready for review after each cycle. Clear box means edits are in-progress:
- [x] Cptr 1 - Intro
- [x] Cptr 2 - Revision history
- [x] Cptr 3 - Terms
- [x] Cptr 4 - Data structs and types
- [x] Cptr 5 - Client init/fini
- [x] Cptr 6 - Sync and data access
- [x] Cptr 7 - Reserved keys
- [x] Cptr 8 - Process-related non-reserved keys
- [x] Cptr 9 - Non-process-related key-vals
- [x] Cptr 10 - Process management
- [x] Cptr 11 - Job management
- [x] Cptr 12 - Events
- [x] Cptr 13 - Data packing/unpacking
- [x] Cptr 14 - Security
- [x] Cptr 15 - Servers
- [x] Cptr 16 - Fabric
- [x] Cptr 17 - Process sets/groups
- [x] Cptr 18 - Tools
- [x] Python Binding

Josh reviews: - will check off the box when review is complete and comments are ready for re-edit. Clear box means that chapter is held for review/review is underway:
- [x] Cptr 1 - Intro
- [x] Cptr 2 - Revision history
- [x] Cptr 3 - Terms
- [x] Cptr 4 - Data structs and types
- [x] Cptr 5 - Client init/fini
- [x] Cptr 6 - Sync and data access
- [x] Cptr 7 - Reserved keys
- [x] Cptr 8 - Process-related non-reserved keys
- [x] Cptr 9 - Non-process-related key-vals
- [x] Cptr 10 - Process management
- [x] Cptr 11 - Job management
- [x] Cptr 12 - Events
- [x] Cptr 13 - Data packing/unpacking
- [x] Cptr 14 - Security
- [x] Cptr 15 - Servers
- [x] Cptr 16 - Fabric
- [x] Cptr 17 - Process sets/groups
- [x] Cptr 18 - Tools
- [x] Python Binding

**Comment by rhc54** [comment]
@jjhursey I have worked thru your last set of comments and the marked chapters are ready for review. I have posted the PR mostly to make the work more visible so that others can assist in the proofreading.

**Comment by rhc54** [comment]
For those wanting to assist in proofreading, I am maintaining (to the best I can) a PDF copy of the draft 
[here](https://github.com/pmix/pmix-standard/files/5071888/pmix-standard.pdf)

**Comment by abouteiller** [comment]
I went over the PR, I assume this document is produced from it?

**Comment by jjhursey** [comment]
With https://github.com/rhc54/pmix-standard/pull/4 I have finished my first review. I'm sure I missed things but tried to sweep up anything I spotted along the way.

**Comment by rhc54** [comment]
Closing this as these passes have been completed.
