### ISSUE TITLE
Review Python Bindings

### ISSUE THREAD

**Issue by jjhursey** [pmix/pmix-standard#313]
The Python bindings have fallen a bit behind the C interface in the v4 standard. This ticket is to track the progress on updating the Python bindings before the v4 release.

C APIs not in the Python Bindings
- [ ] ~PMIx_Data_copy~
- [ ] ~PMIx_Data_copy_payload~
- [ ] ~PMIx_Data_pack~
- [ ] ~PMIx_Data_print~
- [ ] ~PMIx_Data_unpack~
- [x] PMIx_Parse_cpuset_string
- [x] PMIx_server_generate_locality_string
- [x] PMIx_server_generate_cpuset_string

C callback APIs not in the Python Bindings
- [x] ~pmix_connection_cbfunc_t~ (related to `pmix_server_listener_fn_t` which does not have a binding)
- [x] ~pmix_credential_cbfunc_t~ (used for nonblocking form of blocking operation)
- [x] ~pmix_device_dist_cbfunc_t~ (used for nonblocking form of blocking operation)
- [x] ~pmix_dmodex_response_fn_t~ (used for nonblocking form of blocking operation)
- [x] ~pmix_event_notification_cbfunc_fn_t~ (Python uses blocking form)
- [x] ~pmix_hdlr_reg_cbfunc_t~ (Python uses blocking form)
- [x] ~pmix_info_cbfunc_t~ (used for nonblocking form of blocking operation)
- [x] ~pmix_lookup_cbfunc_t~ (used for nonblocking form of blocking operation)
- [x] ~pmix_modex_cbfunc_t~ (Python uses blocking form)
- [x] ~pmix_op_cbfunc_t~ (Python uses blocking form)
- [x] ~pmix_release_cbfunc_t~ (Python internalizes this)
- [x] ~pmix_server_listener_fn_t~ (No binding due to threading model of Python)
- [x] ~pmix_setup_application_cbfunc_t~ (Python uses blocking form)
- [x] pmix_tool_connection_cbfunc_t~ (Python uses blocking form)
- [x] pmix_validation_cbfunc_t~ (Python uses blocking form)
- [x] ~pmix_value_cbfunc_t~ (used for nonblocking form of blocking operation)

Assorted items
- [x] FIx cross-references of APIs to point to their blocking counterpart (instead of the nonblocking counterpart) for consistency.
- [x] Fix cross-references of callbacks to their C counterparts
- [x] Fix name of `PMIx_Allocation_request` Python binding from `allocate` to `allocation_request`
- [x] Fix arguments passed to `Tool.set_server`

**Comment by jjhursey** [comment]
Because of the datatype differences between C and Python I don't think we need APIs for the following:
 * PMIx_Data_copy
 * PMIx_Data_copy_payload
 * PMIx_Data_pack
 * PMIx_Data_print
 * PMIx_Data_unpack

Is that a correct assumption?

**Comment by rhc54** [comment]
FWIW: the C callback functions don't need to be in the Python bindings. For simplicity, given Python's level of thread support, we made the strategic decision to only support _blocking_ APIs for Python.

**Comment by jjhursey** [comment]
### Callbacks used by interfaces with a blocking version (no Python version needed)

For each of these, there is a blocking form of the call, so there is no need for the callback in Python.

 - `pmix_credential_cbfunc_t` is used by `PMIx_Get_credential_nb` so it not needed for Python since there is a blocking interface.
 - `pmix_device_dist_cbfunc_t` is used by `PMIx_Compute_distances_nb` so it not needed for Python since there is a blocking interface.
 - `pmix_dmodex_response_fn_t` is used by `PMIx_server_dmodex_request`. In Python we have the blocking function `Server.dmodex_request` which blocks. So no need for that callback
 - `pmix_info_cbfunc_t` is used by `PMIx_Query_info_nb` so it not needed for Python since there is a blocking interface.
 - `pmix_lookup_cbfunc_t` is used by `PMIx_Lookup_nb` so it not needed for Python since there is a blocking interface.
 - `pmix_value_cbfunc_t` is used by `PMIx_Get_nb` so it not needed for Python since there is a blocking interface.

### Callbacks used in Python APIs, but internalized in the library (no Python version needed)

For these callbacks, they are executed inside the PMIx library after the call completes, or the associated call in Python will block and return the result that would have been provided in the callback (turn the C nonblocking call into a Python blocking call).

 - `pmix_event_notification_cbfunc_fn_t` is used by `pmix_notification_fn_t`. The Python interface is `evhandler` which will execute the callback provided internal to the library. So it is not exposed to Python.
 - `pmix_hdlr_reg_cbfunc_t` is used by `PMIx_Register_event_handler`. The Python interface is `Client.register_event_handler` which has that `evhandler` (`pmix_notification_fn_t`), but the intention is that this function will block until the registration is complete. So no need for this callback function. Additionally this callback is used by `PMIx_IOF_pull` which is in the same situation.
 - `pmix_op_cbfunc_t` is a general operation callback function for a few nonblocking operations. All of this either have blocking counter parts, or the Python interface will block until the operation completes.
 - `pmix_release_cbfunc_t` is used by `pmix_info_cbfunc_t`, `pmix_device_dist_cbfunc_t`, and `pmix_modex_cbfunc_t`. In all of those scenarios it is used to signal to the caller that they can release the data. This is handled internally in the library instead of via a callback.
 - `pmix_setup_application_cbfunc_t` is used by `PMIx_server_setup_application`. This is `Server.setup_application` in Python which is a blocking version of the C version.
 - `pmix_tool_connection_cbfunc_t` is used by `pmix_server_tool_connection_fn_t`. The Python version `tool_connected` which will block and return the status when the routine finishes.
 - `pmix_validation_cbfunc_t` is used by `PMIx_Validate_credential_nb` so it not needed for Python since there is a blocking interface. It is also needed by ``pmix_server_validate_cred_fn_t` which is `validate_credential` in Python. The results that would be part of the callback are returned from the call to this function.
 - `pmix_modex_cbfunc_t` is used by both `pmix_server_fencenb_fn_t` and `pmix_server_dmodex_req_fn_t`.
   - `pmix_server_fencenb_fn_t` is the `fence` Python interface which must return the data normally provided to the callback.
   - `pmix_server_dmodex_req_fn_t` is the `dmodex` Python interface which must return the data normally provided to the callback.

### Open item(s) for investigation

 - `pmix_connection_cbfunc_t` is used by `pmix_server_listener_fn_t`. 
   - `pmix_server_listener_fn_t` is given a socket to listen on this requires a listening thread. Since Python's threading model makes that difficult. I believe the decision was then not to include it - is that correct?

**Comment by rhc54** [comment]
>  Since Python's threading model makes that difficult. I believe the decision was then not to include it - is that correct?

Correct

**Comment by jjhursey** [comment]
PR #314 should have all of the fixes to close this ticket.
