### ISSUE TITLE
Where does evhdlr_ref argument to PMIx_Degregister_event_handler come from?

### ISSUE THREAD

**Issue by dsolt** [pmix/pmix-standard#324]
### Overview

Event handlers are registered with the following call:

pmix_status_t PMIx_Register_event_handler(pmix_status_t codes[], size_t ncodes,
  pmix_info_t info[], size_t ninfo, pmix_notification_fn_t evhdlr, pmix_hdlr_reg_cbfunc_t cbfunc, void *cbdata);

This returns PMIX_SUCCESS on successful completion.  The cbfunc/cbdata can be NULL if the function is treated as blocking.  Doesn't seem to return any handle to the event.

However, deregistering events is done with:

pmix_status_t PMIx_Deregister_event_handler(size_t evhdlr_ref, pmix_op_cbfunc_t);

which takes a size_t evhdlr_ref.  I have no idea where to get this value.

I looked for examples and the only ones I could find (https://github.com/openpmix/openpmix/blob/master/examples/server.c) just used a hard-coded 0 for the evhdlr_ref, which seems if it works, surely only works in the case where you have a single event handler registered.

The text on the 2nd page of the event notification chapter also says:

"Ordering can be specified either by providing the relevant returned event handler registration ID or  using event handler names, if the user specified an event handler name when registering the corresponding event."

This really makes me think I'm missing something obvious here, but then again... the event handler registration ID is a size_t and the user-specified name is a (char*), so you couldn't possibly specify the registration id to something like PMIX_EVENT_HDLR_BEFORE.  This makes me think it doesn't really exist.

### Motivation

Maybe broken API?

### Discussion Items

Am I missing something?
If this is broken, how to fix?  
I don't see how the existing registration API can be used to return this reference... even if we wanted to change the meaning of the return value (which would be really bad), the types wouldn't work out.  The info's can't be used to return values.   It really seems like the API needs an additional parameter?

**Comment by dsolt** [comment]
Ok, I see the issue now...

If cbfunc is NULL, the function call will be treated as a blocking call. In this case, the returned
status will be either (a) the event handler reference identifier if the value is greater than or equal to
zero, or (b) a negative error code indicative of the reason for the failure.

So the types don't match up here... or at least it assumes that pmix_status_t and size_t are interchangeable (maybe the standard says they are?).   So, although I find this API "ugly", I guess the only real issue I have is this one:

"Ordering can be specified either by providing the relevant returned event handler registration ID or using event handler names, if the user specified an event handler name when registering the corresponding event."

**Comment by dsolt** [comment]
Oh and that maybe the example code should be fixed up as well :)

**Comment by rhc54** [comment]
> "Ordering can be specified either by providing the relevant returned event handler registration ID or using event handler names, if the user specified an event handler name when registering the corresponding event."

It's a typo - we only allow precedence directives based on event handler name, not registration ID
