### ISSUE TITLE
Example use of PMIX_INFO_LOAD(&info, PMIX_SESSION_INFO, NULL, PMIX_BOOL) incorrect?

### ISSUE THREAD

**Issue by dsolt** [pmix/pmix-standard#356]
### Overview

I believe info's such as PMIX_SESSION_INFO are declared as bool type (PMIX_BOOL), but in reality they are "true if present".  The text doesn't really say, but it seems to be implied that the value of each info passed to a call is important and saying they have type bool implies they can be passed in as true or false.  However, the examples use code such as:

PMIX_INFO_LOAD(&info, PMIX_SESSION_INFO, NULL, PMIX_BOOL);
PMIX_Get(......, &info, 1,...);

So I suggest we either change the examples to:

bool true_value = true;
PMIX_INFO_LOAD(&info, PMIX_SESSION_INFO, &true_value, PMIX_BOOL);

OR 

we explain in greater detail that some bool types are automatically treated as having a "true" value.

OR 

we change the types of these from PMIX_BOOL to PMIX_TRUE or something like that, then explain in detail that PMIX_TRUE has no value setting  but is always true.

Seems like option #3 would have backward compatibility issues, so I'm assuming option 1 or 2?

**Comment by rhc54** [comment]
Unless I'm mistaken (which is entirely possible), we state in the text at the beginning of the attribute or constants section that boolean attributes default to "true" if present and no value explicitly stated (i.e., a NULL pointer to `PMIX_INFO_LOAD`). If not, then we should make that clear. That policy is extensively used throughout the code and the Standard. We even have a macro (`PMIX_INFO_TRUE`) for properly checking that condition.

**Comment by dsolt** [comment]
For PMIX_INFO_TRUE it says: 

> A pmix_info_t structure is considered to be of type PMIX_BOOL and value true if:
> 
> * the structure reports a type of PMIX_UNDEF, or
> * the structure reports a type of PMIX_BOOL and the data flag is true

The examples however use PMIX_BOOL (not PMIX_UNDEF) and no value.  Maybe there is text somewhere that says that PMIX_INFO_LOAD will default to true if the value pointer is NULL, which is what is going on.  So I think we have to leave this definition as is, but the definition of PMIX_INFO_LOAD (3.2.8.1) needs to be augmented to cover how it handles this special case.

**Comment by rhc54** [comment]
Yeah, we deal with it in `PMIX_INFO_LOAD`:
```c
    if (NULL == data) {
        /* just set the fields to zero */
        memset(&v->data, 0, sizeof(v->data));
        if (PMIX_BOOL == type) {
            v->data.flag = true; // existence of the attribute indicates true unless specified different
        }
    }
```
Not sure how you want to update the text in the Standard to explain it. I believe what we follow is that the presence of a `PMIX_BOOL` attribute defaults to being of `true` value unless the value itself specifies it as `false`.

However, `PMIX_UNDEF` type is a little more difficult. The `PMIX_INFO_TRUE` macro does follow the definition you cite. I suspect the rationale was simply that a type of `PMIX_UNDEF` can't be processed and so we fall back to saying "it is true that the attribute is present". 🤷‍♂️

**Comment by jjhursey** [comment]
To drive this to completion. How about:

* Add the following to `PMIx_Info_load` (v5.0 "Load key and value data into a info struct" section in 3.2.9.1)
> Passing `NULL` as the `data` parameter in `PMIx_Info_load` for a `PMIX_BOOL` `type` parameter will set the associated info to `true`. This is a shorthand for the following where `&true_value` is replaced by `NULL`:
> bool true_value = true;
> PMIX_INFO_LOAD(&info, PMIX_SESSION_INFO, &true_value, PMIX_BOOL);
* Add a cross-reference in the LaTeX connecting `PMIX_BOOL` to this note in `PMIx_Info_load` to make it more easily findable.

If that sounds good then I'll work on a PR.
