### ISSUE TITLE
is​sue with mpirun when​ using through slurm​ / pmix​

### ISSUE THREAD

**Issue by pankajd-57** [pmix/pmix-standard#363]
**Describe your question or clarification request here**
When using slurm-20.11.7 compiled with pmix-3.2.3,  and job is submitted
like below :

srun -N 1 -c 2 --pty /bin/bash

on the allocated compute node, when I execute the below command, I get
the PMI error with return value -46

mpirun -c 2 /bin/hostname

--------------------------------------------------------------------------

A requested component was not found, or was unable to be opened.  This

means that this component is either not installed or is unable to be

used on your system (e.g., sometimes this means that shared libraries

that the component requires are unable to be found/loaded).  Note that

PMIX stopped checking at the first component that it did not find.

Host: cnode9

Framework: psec

Component: munge

--------------------------------------------------------------------------

--------------------------------------------------------------------------

It looks like pmix_init failed for some reason; your parallel process is

likely to abort.  There are many reasons that a parallel process can

fail during pmix_init; some of which are due to configuration or

environment problems.  This failure appears to be an internal failure;

here's some additional information (which may only be relevant to an

PMIX developer):

  pmix_psec_base_open failed

  --> Returned value -46 instead of PMIX_SUCCESS

--------------------------------------------------------------------------

[cnode9:2708617] PMIX ERROR: NOT-FOUND in file server/pmix_server.c at
line 237
### Suggested Clarification

If you have a suggestion for consideration you can put it here. Otherwise, you can delete this section.

### References

Please list specific chapters/sections in the PMIx Standard related to your query.

**Comment by rhc54** [comment]
I realize you are looking for help, but this has nothing to do with the PMIx Standard - it is an Open MPI implementation issue. Please give them time to respond (it is night over here in the US, which is where the majority of the OMPI developers reside).
