### ISSUE TITLE
Should you be able to get PMIX_NSPACE?

### ISSUE THREAD

**Issue by dsolt** [pmix/pmix-standard#371]
### Overview

So our WG is working through all of the different keys that you can PMIx_Get for each realm.  PMIX_NSPACE as listed under the job realm, but interestingly enough the job id cannot be specified using PMIX_NSPACE currently (I just opened another issue suggesting that we allow that).   The OpenPMIx implementation does not seem to allow you to do a PMIx_Get on a proc 
with a rank or PMIX_RANK_WILDCARD or a specific rank.  Now its kind of ridiculous to ask for the PMIX_NSPACE when you have to provide the namespace in proc.nspace.   It's like asking "What's the namespace of 'namespace001'?"   So in our WG, we have removed PMIX_NSPACE from the list of keys that can be queried with PMIx_Get.   I just want to make sure this isn't a problem and make people aware of our intentions now as this minor change is likely to get lost in the very large PR coming out of our WG that moves lots of things around and improves on lots of texts.   So, I'm trying to capture anything that would be a real change in the standard.  As I said though, in this case OpenPMIx doesn't support it currently, so hard to believe we want to keep it there.

### Motivation

Correctness of the standard.

### Discussion Items

Ok to remove from the list of keys you can PMIx_Get or should we allow you to get it and change the implementation to allow it?

**Comment by rhc54** [comment]
It's true that you cannot in general ask to retrieve a `PMIX_NSPACE` for the reasons given. However, you actually can ask to retrieve your own namespace this way by passing a `NULL` for the `proc` argument and `PMIX_NSPACE` as the key. We actually do that in several places where the app doesn't have a global `pmix_proc_t` variable containing its own procID. You can also use that technique to retrieve just your `PMIX_RANK` or the entire `PMIX_PROCID`, depending upon your need.

If you want to discover namespaces (i.e., to find namespaces other than your own), you have to use the `PMIx_Query_info` API - e.g., to retrieve the namespaces with the current session.

**Comment by dsolt** [comment]
Ok, I did not think to try passing a NULL proc.   Since this is supported I think we will need to keep PMIX_SPACE is the list of keys,but will need to explain the details of how it must be used.  I'm leave this issue open until I actually appy that change so we don't forget.

**Comment by dsolt** [comment]
Done.  I also added a note that there are 3 attributes/keys that can be used both to specify a realm target and also queried, since this could be a bit of a stumbling block for users trying to understand how they work.
