### ISSUE TITLE
What should PMIX_CMD_LINE specify for a PMIx rank started with PMIx_spawn()

### ISSUE THREAD

**Issue by dsolt** [pmix/pmix-standard#372]
### Overview

PMIX_CMD_LINE says:

`Command line used to execute the specified job (e.g., "mpirun -n 2 –map-by foo ./myapp : -n
25 4 ./myapp2").`

What should it return if the job was created with PMIx_Spawn?

Some options:

1.  PMIX_ERR_NOTFOUND
2. NULL string
3. PMIx_Spawn or PMIx_spawn_nb
4. The command line specified in PMIx_spawn_nb (this doesn't seem to be the intention of PMIX_CMD_LINE though)
5. ?? something else ??

### Motivation

Just want to specify what the value should be in all cases.

### Discussion Items

Obviously not too important, but if any tools are clients are using this, we wouldn't want them to roll over because they asked about a spawned process and didn't get an answer or got a NULL string, etc.

**Comment by rhc54** [comment]
You get the string created by joining the argv arrays of all the `pmix_app_t` objects passed in the call to `PMIx_Spawn`, each `pmix_app_t` separated by a `:` - e.g., "app1 arg0 arg1 : app2 arg2 arg3". I suppose one could start it all with "spawn:" just to indicate it was a spawn call.

**Comment by dsolt** [comment]
I like that.   I can drive the PR to standardize this and PR to add the spawn: to OpenPMIx if nobody objects.

**Comment by dsolt** [comment]
PR #377
