### ISSUE TITLE
What should PMIX_PARENT_ID return for non-spawned processes

### ISSUE THREAD

**Issue by dsolt** [pmix/pmix-standard#373]
### Overview

You can PMIx_Get the PMIX_PARENT_ID of a process to see who spawned it:

`Process identifier of the parent process of the specified process - typically used to identify the application process that caused the job containing the specified process to be spawned (e.g., the process that called PMIx_Spawn).`

What should you get if the process was not spawned?  

1. PMIX_ERR_NOTFOUND
2. Itself
3. A process with NULL namespace and PMIX_RANK_UNDEF?

### Motivation

Just trying to cover all cases so clients know what to expect.

### Discussion Items

I tend to lean towards the first choice. (it will fail to find it).   It's hard to say then if it is because the implementation doesn't support it or if its because it wasn't a spawned process.  There is another key that can be used to query if a process was spawned though, so that should help.

**Comment by rhc54** [comment]
I guess you're asking what should be returned if I'm a tool started off the cmd line, and therefore not spawned by some other process like the resource manager? The answer is indeed the first option (`PMIX_ERR_NOT_FOUND`). This is a behavior used in a number of places.

**Comment by dsolt** [comment]
Thanks.   Then I think I'll post a PR to standardize that.  Should be a one-line change, but since its a real addition to the standard I'll probably open a new PR for this change (rather than lumping it into our bigger WG changes to this chapter)

**Comment by dsolt** [comment]
I notice that the tools chapter says this about PMIX_PARENT_ID:

 The \ac{IL} should register for this event after completing \refapi{PMIx_tool_init} - the initiator's namespace can be obtained via a call to \refapi{PMIx_Get} with the \refattr{PMIX_PARENT_ID} key.  Note that this feature will only be available if             the spawned \ac{IL} is local to the initiator.

Is this "this feature" referring to the ability to register for PMIX_EVENT_JOB_END or is it referring to the ability to get PMIX_PARENT_ID?  I'm going to assume the former, but if that's not true, we should include that bit of info in the PMIX_PARENT_ID description. 

I also added a terms and conventions definition of tool.  Not sure why we never had one?  Hard to believe that was an oversight, where we stuck on that definition and decided to do it later?

Anyway, PR created #376
