### ISSUE TITLE
Update infrastructure on v4 branch

### ISSUE THREAD

**Issue by rhc54** [pmix/pmix-standard#388]
Would it be possible to update the infrastructure on the v4 branch? I note there are significant differences between master and v4 branches - e.g., the return code and "signature" macros. This makes new text in the v4 branch difficult to bring forward to master without a lot of editing.

I don't think it would be terribly hard to do - but don't want to invest the effort if it isn't something we want to do. My thought was to simply add the missing macros without editing the existing text to use them. Then, new text could use the newer macros, making the changes easy to cherry-pick to master.

Make sense?

**Comment by jjhursey** [comment]
Based on the discussion during the May 8, 2023 PMIx ASC Q2 meeting:
 * We are hoping that the v4.2 (and possible v4.3) release will be the end of the line for the `v4` series so we are weighing the effort needed to move over the infrastructure vs the benefit of doing so.
 * We decided to not move the infrastructure over at this time.
 * We might revisit this if it becomes more of an issue than expected
