### ISSUE TITLE
Padding of pmix_value_t

### ISSUE THREAD

**Issue by jjhursey** [pmix/pmix-standard#399]
### Overview

In our discussion of the PMIx ABI we [started discussing](https://github.com/pmix/pmix-standard/issues/365#issuecomment-1095269304) if we needed to add padding to the `pmix_value_t`.

### Motivation

Adding padding would stabilize the size of the `pmix_value_t` making it usable for applications that want to pass elements of this datatype between processes (e.g., via shared memory) that may have been compiled with different PMIx implementations.

### Discussion Items

 * Do we need to specify padding in the data structure or just specify the size in the standard?
 * The amount of padding needed is going to be compiler/architecture-specific. How do we control for this from an implementation perspective?

**Comment by jjhursey** [comment]
The current `pmix_value_t` is 32 bytes (Apple clang version 12.0.5, Intel Mac / GCC 8.4.1, IBM power9), which is already padded by 6 bytes by the compiler because the `type` is only `2` bytes
```
pmix_value_t : 32
-------------:-------
pmix_value_t :  2 type
pmix_value_t : 24 data
-------------:-------
```

The proposal is to request that the size of the `pmix_value_t` structure be exactly 32 bytes. An implementation may pad the structure to reach that value.

We would add the following wording to the PMIx Standard:
 > The size of the pmix_value_t must remain constant on a given platform regardless of the compiler. The pmix_value_t is 32 bytes with 24 bytes reserved for the data union member. An implementation may add a padding member to the structure to achieve the required 32-byte size.
 > Changes to the pmix_value_t must not increase the size of the data structure. It is strongly recommended that if the structure needs to be extended in a way that would increase its size then a pointer be used instead.

**Comment by jjhursey** [comment]
An implementation in OpenPMix would make the following change:
```diff
 typedef struct pmix_value {
-    pmix_data_type_t type;
-    union {
+   union pmix_value_t_data {
       ... Bunch of fields
     } data;
+    pmix_data_type_t type;
+ #define PMIX_VALUE_T_PADDING 32
+    char padding[PMIX_VALUE_T_PADDING - (sizeof(union pmix_value_t_data) + sizeof(pmix_data_type_t))];
+ #undef PMIX_VALUE_T_PADDING
} pmix_value_t;
```

Note I needed to move the `type` below the union so that I could control the padding. The compiler wants to pad the `2` bytes for the `type` to `8` if it occurs before the union. If I move it after the union it will allow me to adjust the padding as expected.

Instead of codifying that logic in the PMIx Standard, I think we can leave the implementation of the "must be 32 bytes" rule up to the implementation. They could use the padding trick above, or if they have other techniques then they can apply those.

**Comment by jjhursey** [comment]
Added language to https://github.com/pmix/pmix-standard/pull/375

**Comment by rhc54** [comment]
> Note I needed to move the `type` below the union so that I could control the padding. The compiler wants to pad the `2` bytes for the `type` to `8` if it occurs before the union. If I move it after the union it will allow me to adjust the padding as expected.

Hmmm...unfortunately, that introduces an ABI break - yes? We now reordered the `pmix_value_t` fields, which means any shmem-based system will be broken.

**Comment by jjhursey** [comment]
Good point. The alternative, below, works and is more explicit albeit more complex.
```diff
+ #define PMIX_VALUE_T_PADDING 32
+ #define PMIX_VALUE_T_PADDING_TYPE 8
+ #define PMIX_VALUE_T_PADDING_DATA (PMIX_VALUE_T_PADDING - PMIX_VALUE_T_PADDING_TYPE)
 typedef struct pmix_value {
     pmix_data_type_t type;
+     char type_padding[PMIX_VALUE_T_PADDING_TYPE - sizeof(pmix_data_type_t)];
-    union {
+    union pmix_value_t_data {
       ... Bunch of fields
     } data;
+    char data_padding[PMIX_VALUE_T_PADDING_DATA - sizeof(union pmix_value2_data_t)];
} pmix_value_t;
+ #undef PMIX_VALUE_T_PADDING_DATA
+ #undef PMIX_VALUE_T_PADDING_TYPE
+ #undef PMIX_VALUE_T_PADDING
```

**Comment by rhc54** [comment]
Hmmm...I think that still breaks the ABI, doesn't it? You have moved the location of the union within the object. So if I go to the object's address and take the first two bytes as the type, I then expect the union to start at the next byte. Are you padding the `type` field because the union won't be at that location due to compiler alignments? Somehow, I thought that the compiler didn't internally align the individual fields of a struct, but only the address of the struct itself (with the fields addressed via offset from that point).

**Comment by jjhursey** [comment]
The compiler will pad the individual elements. I found these [two](http://www.catb.org/esr/structure-packing/#_structure_alignment_and_padding) [articles](https://devtut.github.io/c/structure-padding-and-packing.html) helpful.

So the `type` is already blocked out into an 8-byte space even though it takes 2 bytes. The union starts at the 8-byte offset. Basically, this is codifying what the compiler is already doing.

Inspecting via gdb (My test program calls the structure `pmix_value2_t` but it matches the code in the previous comment):
```
(gdb) p &v2
$8 = (pmix_value2_t *) 0x7fffffffe270
(gdb) p &v2.type
$9 = (pmix_data_type_t *) 0x7fffffffe270
(gdb) p &v2.type_padding
$10 = (char (*)[6]) 0x7fffffffe272
(gdb) p &v2.data
$11 = (union pmix_value2_data_t *) 0x7fffffffe278
(gdb) p &v2.data_padding
$12 = (char (*)[]) 0x7fffffffe290

(gdb) p sizeof(v2)
$13 = 32
(gdb) p sizeof(v2.type)
$16 = 2
(gdb) p sizeof(v2.type_padding)
$17 = 6
(gdb) p sizeof(v2.data)
$14 = 24
(gdb) p sizeof(v2.data_padding)
$15 = 0
```

| Field | Address | Offset | Length |
| -- | -- | -- | -- |
| type | 0x7fffffffe270 | 0 | 2
| type_padding | 0x7fffffffe272 | 2 | 6
| data | 0x7fffffffe278 | 8 | 24
| data_padding | 0x7fffffffe290 | 32 | 8

**Comment by jjhursey** [comment]
I forgot to add the breakdown of the existing `pmix_value_t` (without the padding members)
```
(gdb) p &v
$1 = (pmix_value_t *) 0x7fffffffe200
(gdb) p &v.type
$2 = (pmix_data_type_t *) 0x7fffffffe200
(gdb) p &v.data
$3 = (union {...} *) 0x7fffffffe208
(gdb) p sizeof(v)
$4 = 32
(gdb) p sizeof(v.type)
$5 = 2
(gdb) p sizeof(v.data)
$6 = 24
```

| Field | Address | Offset | Length |
| --- | --- | --- | --- |
| type | 0x7fffffffe200 | 0 | 2 |
| data | 0x7fffffffe208 | 8 | 24 |

So you can see that the compiler already put in 6 bytes of padding between the `type` and `data` members of the `pmix_value_t` structure.
