### ISSUE TITLE
What does PMIX_REINCARNATION actually mean?

### ISSUE THREAD

**Issue by krempel-pt** [pmix/pmix-standard#402]
> PMIX_REINCARNATION "pmix.reinc" (uint32_t)
> Number of times this process has been re-instantiated - i.e, a value of zero indicates that the
process has never been restarted. 5

This is the only description I can find in the standard. (Three times, each time with the weird '5' at the end ;-))

There is no word about re-instantiation of processes or what this means. Is a re-instantiated process a client that called `PMIX_Init()` more than once? Does it need to have called `PMIX_Finalize()` in between so it counts as a new instance? What about a *clone* in this context?

What is the intended use case for this value, making it important enough to be non-optional at namespace registration?

### References
6.1.4
16.2.3
C.8.2

**Comment by rhc54** [comment]
It is the number of times that particular process has been started by the host environment. It is used in fault tolerant applications as a way of knowing that "this process died and was restarted N times". It has nothing to do with calling `PMIx_Init`.

**Comment by krempel-pt** [comment]
So do I understand it correctly that `PMIX_REINCARNATION` is only to be increased if the host environment will for some reason spawn again the same process, defined by namespace/rank combination (so started with the same environment got from calling `pspmix_server_setupFork()` with the same namespace/rank)?

So for a host environment not supporting such a respawn mechanism it is totally fine to set PMIX_REINCARNATION to 0 for all processes and leave it alone?

**Comment by rhc54** [comment]
You should set `PMIX_REINCARNATION` to zero for each process when first launching an application. If you support process restart upon failure, then you would increment that value for the process being restarted each time you restart it (providing the value when you registered the nspace to update the information). If you don't support process restart, then you obviously would never increment it.

I don't think the Standard currently talks much about how to update job-level information in support of fault tolerance. Probably something worthy of its own little chapter. We have functioning support now built into Open MPI's v5 series, so perhaps that can help guide things.

HTH

**Comment by krempel-pt** [comment]
Yes, many thanks.
