### ISSUE TITLE
Network traffic packets documentation

### ISSUE THREAD

**Issue by victorsndvg** [pmix/pmix-standard#404]
Hello,

I would like to sniff the OMPI network traffic from outside the MPI application. This includes the OOB traffic too, and I think this is being done by PMIx.

I would like to know how application data is packaged. I don't know if this is already documented or where I can't start looking at.

Please, is there any official documentation, or paper, or presentation or picture about PMIx packets data?

Sorry if this a basic question or if it was already answered. Any clarification will be very appreciated.

Thanks in advance for your help.

BR,
Víctor.

**Comment by jjhursey** [comment]
This is a question for the Open MPI implementation (https://github.com/open-mpi/ompi) and possibly the OpenPMix implementation (https://github.com/openpmix/openpmix). The PMix Standard does not define a network wire protocol (at this time any way). So the specifics of how clients and servers communicate is left to the specific implementation.
