### ISSUE TITLE
Best way to get job rank, local rank and hostname information of all processes in a job.

### ISSUE THREAD

**Issue by darbyShaw** [pmix/pmix-standard#413]
Hello,

I would like to get the local rank, job rank and the hostname associated with all processes in a job in a single API call to the PMIx server.
I see several ways of doing this as follows:
1.  Get all nodes using PMIx_resolve_nodes. Then for each node get job ranks on each node called local peers using PMIX_LOCAL_PEERS key on each node. After that for each rank on a node, get the local rank using PMIX_LOCAL_RANK.
2.  Get hostname and job rank using the query PMIX_QUERY_PROC_TABLE that returns an array of pmix_proc_info_t. But this info does not have the local rank of the process. So separately query the local rank for each process.

I would like to avoid having to execute PMIx_Get for every process in the job. 
Are there other ways to get the information more efficiently, optimally in a single API call?

Thank you very much in advance.

**Comment by rhc54** [comment]
If every process in your job makes that request, it is (a) going to consume a lot of memory for a large job and (b) take some time to complete. All the server does is effectively call "get" for the info you request - for any info it doesn't have, it then refers the request to the host for resolution before responding. You do avoid the overhead of thread protection on each call, but that is likely a small component of the response time.

Can you tell us something about what you intend to do with this info? There might be a more direct way to achieve your objective.

**Comment by darbyShaw** [comment]
I would like to collect the information to make the initial wireup that comprises of a backend thread with a listening socket at each process. Since we have not yet explored whether the backend thread can be completely eliminated using PMIx event notification mechanism, we would like to keep it. The hostname, job rank and local rank are used as addressing information for the backend thread where the local rank is used to locate a port within a range of ports.

You are right that a lot of memory would be required to store such information, but there might be a launch speed up if such information is available locally in process memory. It might get faster than doing a global fence operation to store all job related information locally at each PMIx server and then query independently for the job rank, hostname and local rank for each process during building connections.
It would be nice to have the job rank, hostname and local rank information in a single query to the local PMIx server even if done per process instead of the whole job at once.

**Comment by rhc54** [comment]
Got it. You could do it on an as-needed basis when you have to send a message to the remote proc, but that might require some code changes.

You could infer local rank by counting ranks on a node from the proctable since you only need consistency - probably faster that way. Local rank is assigned by the host, usually by just counting them in order

**Comment by darbyShaw** [comment]
Thank you. Your comment made things much easier.
