### ISSUE TITLE
Payload Field of the pmix_iof_cbfunc_t Signature

### ISSUE THREAD

**Issue by darbyShaw** [pmix/pmix-standard#421]
Hello all,

Found a very minor inconsistency. In the PMIx standard document (4.1), the signature of pmix_iof_cbfunc_t has payload as char* but in the code it is pmix_byte_object_t*.  I use the PMIx reference library from the master branch at 
git master @ 5ea332842a2b5ec7c6b8675c119e0a27697fed5c , so may be the signature changes in the next version.
Thank you.

**Comment by rhc54** [comment]
Yeah, that's an error - it needs to be the `pmix_byte_object_t`. If you read the "advice to users", it even says there that the payload can consist of multiple strings and may not be NULL terminated, so it cannot be a `char*`.

**Comment by abouteiller** [comment]
This will need to be an errata.

**Comment by dsolt** [comment]
See #486 

I looked over the rest of the description and did not see anything else that needs to change.  
The Python bindings were already correct.
