### ISSUE TITLE
Add const qualifier to all strings not meant to be modified

### ISSUE THREAD

**Issue by krempel-pt** [pmix/pmix-standard#426]
### Overview

In the signatures of some functions `char *` is used as type for strings clearly not meant to be modified by the function. In such cases in general the `const` qualifier should be added.

### Motivation

For example using the functions `PMIx_server_define_process_set()` and `PMIx_server_delete_process_set()` with a `const char*` string leads to a GCC compiler warning [-Wdiscarded-qualifiers]. This is avoidable and should be done, since this function clearly should not alter the string, most probably it will just copy it.

In other cases like that (e.g. `PMIx_Info_list_add()`) `const` is already in place, so perhaps it has just been missed.

### Discussion Items

To be honest, I don't see much room for discussion here. Would be interesting, why this not already happened, whether I am the first one struggling on this and if there is a good reason not to do this, that I cannot see.

A (hopefully) complete list of functions where I see the issue:
- `PMIx_Get_attribute_string(char *attributename)`
- `PMIx_Get_attribute_name(char *attributename)`
- `PMIx_Data_print(char **output, char *prefix, void *src, pmix_data_type_t type)`
- `PMIx_Register_attributes(char *function, pmix_regattr_t attrs[], size_t nattrs)`
- `PMIx_server_define_process_set(const pmix_proc_t members[], size_t nmembers, char *pset_name)`
- `PMIx_server_delete_process_set(char *pset_name)`

**Comment by rhc54** [comment]
FWIW: I already did these in OpenPMIx for the same reason. I believe it is mentioned in the EXCEPTIONS file, and I know I've brought it over here before somewhere (I forget where - might be in one of the issues).

I'm unaware of any problem in doing this.
