### ISSUE TITLE
Question about PMIx_Register_event_handler()

### ISSUE THREAD

**Issue by gvallee** [pmix/pmix-standard#46]
A question that we may want to clarify: Based on my understanding, we have specific requirements when using event handlers to guarantee progress. There is no text about this in the ```PMIx_Register_event_handler()``` specification. Did I misunderstood? If not, is it something we want to clarify here? If not, is it something we want to clarify somewhere else?

**Comment by rhc54** [comment]
It is in the preceding section (the generalized intro to the chapter), but you are correct that we should highlight it again here.
