### ISSUE TITLE
PMIx_Server_register_nspace(): static members?

### ISSUE THREAD

**Issue by gvallee** [pmix/pmix-standard#47]
The current says:
````
The caller must also provide the number of local processes that will be launched within this
namespace. This is required for the PMIx server library to correctly handle collectives as a
collective operation call can occur before all the local processes have been started.
````
Is it possible to change the number of local processes later on? If not, I would assume that we are required to have a static group of local processes. If so, I believe it is a fairly strong requirements (and I am not opposed to it) and should be clarify, even if simply to say something like: the group of local processes can be expended after initial deployed using the ```PMIx_Spwan()``` function. Even if ```PMIX_Spawn()``` is working at the job level, not at the process level, which raises other questions.

**Comment by rhc54** [comment]
You cannot dynamically change the number of local processes in that nspace. Processes started by ```PMIx_Spawn``` are in their own nspace, not that of their parent. I have no problem clarifying this point.

**Comment by rhc54** [comment]
Hmmm....actually, you could potentially change that number - e.g., by migrating a process to an existing location using the job control API. Let me try to capture this in an advice to users as it is critical that they not make such a change during a collective operation.
