### ISSUE TITLE
Denote when an API was added to the standard

### ISSUE THREAD

**Issue by jjhursey** [pmix/pmix-standard#5]
Reading the standard, especially as a we move forward, it would be helpful to have a notation about when an API/attribute was first introduced to the PMIx standard.

`Appendix A - Document Revision History` would be a good place. We could also add a notation (maybe in the margin) noting the version of the PMIx standard when this API was first introduced.

**Comment by abouteiller** [comment]
I support the idea of the margin note (in addition to the traditional appendix). I was working with OpenACC some days ago and knowing in what version what API gets introduced at the same place the API is described was immensely useful.

**Comment by rhc54** [comment]
Do we have this now? Or do we need to add a macro to do it?

**Comment by jjhursey** [comment]
I am tinkering with an attribute to add to the definition. I'm hoping to have that ready this week. It'll place a "introduced in version X" in the margin next to the definition.

**Comment by jjhursey** [comment]
The version is placed in the left hand margin between the page number. All of the API's are marked in the `Format` block at the `C` marker.
We can also mark the attributes, but I didn't in this pass. We can do that as a separate activity.

**Comment by jjhursey** [comment]
Fixed by PR #40
