### ISSUE TITLE
Move History section to front?

### ISSUE THREAD

**Issue by rhc54** [pmix/pmix-standard#55]
@jjhursey Should we move the history section towards the front of the doc? It occurred to me that someone might benefit from a quick way to see what has changed since the last version was released, and that we could provide a summarized description of that in the history.

**Comment by jjhursey** [comment]
Yeah that's a good idea. I've seen other standards (OpenACC) put it at the end of the Introduction chapter as separate sections.
```
1.5 Version 1.0:
1.6 Version 2.0
```
Notice they inverted the order so it's chronological now. Makes it easier to drop in a new section for the new version without updating the old section numbers.

I like that better than having a history chapter after the intro.

I'll take a pass at it in a moment and post a PR.
