### ISSUE TITLE
Constants with 'values'

### ISSUE THREAD

**Issue by abouteiller** [pmix/pmix-standard#72]
In many places, the definition of PMIX constants come with 'values'. 

For example pp 14:14 
`PMIX_MAX_NSLEN 255 Maximum namespace string length as an integer.`

What is the rationale for standardizing that  the NSLEN will always be 255 ? I recommend not defining the numeric values in the standard document.

**Comment by rhc54** [comment]
I'm unaware of that happening in _many_ places, but there are a few standard values that we require. The example you cite sets the size of the namespace array in several structures. Let's talk on today's call about whether or not that is required to be a specific value or can be left to implementers - I'm a little concerned about apps that want to pass values and find themselves in an overly constrained environment.

**Comment by jjhursey** [comment]
Per call:
 * @abouteiller will review the document to find all of the constant values. May want to remove constant value from the standard. Need to decided on a case-by-case basis.
 * Some cleanup in PR #75
 * For `PMIX_MAX_NSLEN` suggested that we specify a 'minimum' length and let implementations increase this value if needed. Suggested 64 characters as an advice to implementors.
  - Some discussion about what the purpose of a value here is. Implementors may find this valuable.

**Comment by rhc54** [comment]
@abouteiller Running into something I don't know - how would you typedef pmix_key_t as a char array of constant size? From what I can find, it would look something like this:
```c
typedef char pmix_key_t[PMIX_MAX_KEYLEN+1];
```
However, I'm seeing this rather strong warning:
```
However, this is probably a very bad idea, because the resulting type is an
array type, but users of it won't see that it's an array type. If used as a
function argument, it will be passed by reference, not by value, and the
sizeof for it will then be wrong.
```

Any thoughts?

**Comment by abouteiller** [comment]
Here is a full list of the value-defined constants. Checked are those proposed for removal of the 'value' part. 

`
$ ag --tex constitemvalue
Chap_API_Struct.tex
`

- [ ] 29:\declareconstitemvalue{PMIX_MAX_NSLEN}{255} **change to 63**
- [ ] 32:\declareconstitemvalue{PMIX_MAX_KEYLEN}{511} **change to 63**
- [ ] 342:\declareconstitemvalue{PMIX_RANK_UNDEF}{UINT32_MAX} **keep value defined as user is free to use non-defined values and need to know**
- [ ] 346:\declareconstitemvalue{PMIX_RANK_WILDCARD}{UINT32_MAX-1}
- [ ] 349:\declareconstitemvalue{PMIX_RANK_LOCAL_NODE}{UINT32_MAX-2}
- [x] 385:\declareconstitemvalue{PMIX_PROC_STATE_UNDEF}{0}
- [x] 388:\declareconstitemvalue{PMIX_PROC_STATE_PREPPED}{1}
- [x] 391:\declareconstitemvalue{PMIX_PROC_STATE_LAUNCH_UNDERWAY}{2}
- [x] 394:\declareconstitemvalue{PMIX_PROC_STATE_RESTART}{3}
- [x] 397:\declareconstitemvalue{PMIX_PROC_STATE_TERMINATE}{4}
- [x] 400:\declareconstitemvalue{PMIX_PROC_STATE_RUNNING}{5}
- [x] 403:\declareconstitemvalue{PMIX_PROC_STATE_CONNECTED}{6}
- [x] 406:\declareconstitemvalue{PMIX_PROC_STATE_UNTERMINATED}{15}
- [x] 410:\declareconstitemvalue{PMIX_PROC_STATE_TERMINATED}{20}
- [x] 413:\declareconstitemvalue{PMIX_PROC_STATE_ERROR}{50}
- [x] 417:\declareconstitemvalue{PMIX_PROC_STATE_KILLED_BY_CMD}{PMIX_PROC_STATE_ERROR+1}
- [x] 420:\declareconstitemvalue{PMIX_PROC_STATE_ABORTED}{PMIX_PROC_STATE_ERROR+2}
- [x] 423:\declareconstitemvalue{PMIX_PROC_STATE_FAILED_TO_START}{PMIX_PROC_STATE_ERROR+3}
- [x] 426:\declareconstitemvalue{PMIX_PROC_STATE_ABORTED_BY_SIG}{PMIX_PROC_STATE_ERROR+4}
- [x] 429:\declareconstitemvalue{PMIX_PROC_STATE_TERM_WO_SYNC}{PMIX_PROC_STATE_ERROR+5}
- [x] 432:\declareconstitemvalue{PMIX_PROC_STATE_COMM_FAILED}{PMIX_PROC_STATE_ERROR+6}
- [x] 435:\declareconstitemvalue{PMIX_PROC_STATE_CALLED_ABORT}{PMIX_PROC_STATE_ERROR+7}
- [x] 438:\declareconstitemvalue{PMIX_PROC_STATE_MIGRATING}{PMIX_PROC_STATE_ERROR+8}
- [x] 441:\declareconstitemvalue{PMIX_PROC_STATE_CANNOT_RESTART}{PMIX_PROC_STATE_ERROR+9}
- [x] 444:\declareconstitemvalue{PMIX_PROC_STATE_TERM_NON_ZERO}{PMIX_PROC_STATE_ERROR+10}
- [x] 447:\declareconstitemvalue{PMIX_PROC_STATE_FAILED_TO_LAUNCH}{PMIX_PROC_STATE_ERROR+11}
- [x] 595:\declareconstitemvalue{PMIX_INFO_REQD}{0x0001}
- [x] 625:\declareconstitemvalue{PMIX_ALLOC_EXTERNAL}{128}
- [x] 967:\declareconstitemvalue{PMIX_DATA_TYPE_MAX}{500}

**Comment by rhc54** [comment]
You are quite correct - none of those states or other values should be specified. Even the rank values can be left open with an advice to use the names and not the absolute value.

The only thing I think we cannot change is the size of pmix_rank_t. Which values are undef, wildcard, etc. can be left to the implementer, with the note that it may differ between implementations.

**Comment by rhc54** [comment]
@abouteiller @jjhursey Any thoughts on what to do with ```pmix_key_t```?

**Comment by rhc54** [comment]
No compiler complaints - I haven't tested it yet. More just an observation made by someone indicating that ```sizeof(pmix_key_t)``` would return an incorrect value. I'll test it first and report back. If it is true, I'd opt for your second alternative.

**Comment by rhc54** [comment]
Well, I don't really know what that person was talking about. Here is a program I wrote to test it:
```c
#include <stdio.h>

typedef char foo_t[256];

int main(int argc, char **argv)
{
	foo_t myval;
	int sz = sizeof(myval);

	fprintf(stderr, "Size: %d\n", sz);
}
```
and the output I received:
```
$ ./keys
Size: 256
$
```
Let me check what happens when I pass it to a function.

**Comment by rhc54** [comment]
Okay, here is what they meant. Consider the following code:
```c

typedef char foo_t[256];

static int boo(foo_t myfoo)
{
	int sz = sizeof(myfoo);
	fprintf(stderr, "Size in boo: %d\n", sz);
	return 0;
}

int main(int argc, char **argv)
{
	foo_t myval;
	int sz = sizeof(myval);

	fprintf(stderr, "Size: %d\n", sz);

	boo(myval);
}
```
When I compile this with gcc 7.3.1, I get the following warning:
```shell
$ gcc -o keys keys.c
keys.c: In function 'boo':
keys.c:7:17: warning: 'sizeof' on array function parameter 'myfoo' will
return size of 'char *' [-Wsizeof-array-argument]
  int sz = sizeof(myfoo);
                 ^
keys.c:5:22: note: declared here
 static int boo(foo_t myfoo)
                      ^~~~~
$
```
However, the result (minus the warning) is no worse than passing an array:
```c
#include <stdio.h>

typedef char foo_t[256];

static int boo(foo_t myfoo, char *mybar)
{
	int sz = sizeof(myfoo);
	int sz2 = sizeof(mybar);
	fprintf(stderr, "Size in boo: %d %d\n", sz, sz2);
	return 0;
}

int main(int argc, char **argv)
{
	foo_t myval;
	int sz = sizeof(myval);
	char bar[256];
	int sz2 = sizeof(bar);

	fprintf(stderr, "Size: %d %d\n", sz, sz2);

	boo(myval, bar);
}
```
which yields:
```shell
$ ./keys
Size: 256 256
Size in boo: 8 8
```
So I'm torn - any thoughts? I suppose one point to consider is that there is no reason for anyone to call ```sizeof(pmix_key_t)``` as it is a known defined constant - and so if you get a warning, you can simply correct your code.

**Comment by abouteiller** [comment]
Yes, the warning is useful and correct, but does not appear to preclude the desired usage we entail for the datatype as a static structure member.
