### ISSUE TITLE
pmix_rank_t is standardized to 32 bit

### ISSUE THREAD

**Issue by abouteiller** [pmix/pmix-standard#73]
In section 3.2.1 pp 17:22, `pmix_rank_t` is defined to be equivalent to `uint32_t`. Accordingly, the associated constants are set to `UINT32_MAX-1` etc.

As systems grow larger, this 32 bit limitation may come back to haunt us. 

On the other hand, variadic size for this parameter may render cross-version compilation and/or server-client interoperability problematic?

**Comment by jjhursey** [comment]
Per call:
Decided that 4 billion is a safe limit for now. Increasing it causes problems, and hitting this limit is unlikely in the near future. Eventually we will need to re-evaluate.
