### ISSUE TITLE
Before 3.3.6: definition of a key

### ISSUE THREAD

**Issue by abouteiller** [pmix/pmix-standard#74]
Right above, we have the 'value' manipulation functions and type definition (3.3.6 pp 27:1). Reading this made me realize that there is no symmetrical definition of a 'key' type. 

The 'key' type is implicitly defined at other places (3.2.10 pp22:5, 3.3.4 pp 25:4) as being `char key[PMIX_MAX_KEYLEN+1];`

I propose adding between 3.3.5 and 3.3.6 a formal definition of the key type. In pmix2x, it may be to late to add the formal addition of the `pmix_key_t` type as an equivalent type to `char key[PMIX_MAX_KEYLEN+1];`, but it may be added to pmix3x. For 2x, we may want to simply define that a key is `char key[PMIX_MAX_KEYLEN+1];`

**Comment by jjhursey** [comment]
Per call:
 * Set a minimum number of characters for PMIX_MAX_KEYLEN. Suggest 64 characters (as advice to implementors or inline).
 * Define a `pmix_key_t` type.

**Comment by rhc54** [comment]
Completed via #78
