### ISSUE TITLE
Advice to multiple type of implementors

### ISSUE THREAD

**Issue by abouteiller** [pmix/pmix-standard#76]
The macro 'advice to implementors' is too crude for the PMIx ecosystem. We have multiple 'implementors' we are talking to, and we may want have more targeted advices.
1. PMIx server implementors
2. RM implementors
3. PMIx library implementors

Meanwhile, PMIx clients (e.g. MPI) are the 'user' in 'advice to users' 

We should review the current advice to implementors and users and make sure they are properly categorized and define new categories for the relevant implementor types.

**Comment by rhc54** [comment]
I'm not sure I understand the difference between these groups. Maybe let me try to rephrase a bit to clear things in my fossil brain:

1. Those who implement their own PMIx library - this has to include both client and server sides
1. Those who integrate PMIx into their resource manager or scheduler - they are primarily concerned with supporting the PMIx server functions
1. Those who use PMIx as a client - this includes apps, tools, and system management subsystems

I propose that we change our banners/definitions to reflect that:

1. advicepmiximpl - advice to someone implementing their own PMIx lib
1. advicerm - advice to those integrating PMIx into their RM or scheduler
1. adviceuser - advice to those using PMIx

Make sense?

**Comment by abouteiller** [comment]
Yep, looks good.

**Comment by rhc54** [comment]
If @jjhursey doesn't have time to make the new macros, I'll take a cut at it tomorrow and then work thru the doc.

**Comment by rhc54** [comment]
Done!
