### ISSUE TITLE
mark Optional and PRI attributes as non-standard binding

### ISSUE THREAD

**Issue by abouteiller** [pmix/pmix-standard#77]
In many functions we take optional attributes, and we also expose the attributes that the PRI uses. In both cases, (and in contrast with the required attributes), these attributes are not required from an implementation.

Proposition is to 
1. reorder the attributes in all functions so that REQUIRED attributes are defined first
2. add to terms and definitions a new 'color box' similar to the advice to implementor type of box to denote optional and PRI attributes
3. Use the above term and definition space to clarify what we mean by optional and PRI defined attributes (i.e. optional are not required, but if provided must do what is depicted; PRI refer to the specific implementation of the reference server, and a rationale as to why we present them in the standard). 
4. clarify (at the same place) that in any case a compliant implementation does not have to support these attributes.

**Comment by rhc54** [comment]
IIRC, we proposed to describe the _optional_ attributes in "advice to RM implementors" and drop the "optional" - i.e., we would say this is what a "quality implementation" would provide (without using that term - I forget what we agreed to use in its place).

I agree we need some clarifying text in the early part of the doc to explain why PRI is included and a clearer way of denoting those sections. We'll have to see if PRI-supported attributes are automatically considered _required_ or if some should have overlapping entries in the optional section.
