### ISSUE TITLE
How collective is PMIx_connect

### ISSUE THREAD

**Issue by abouteiller** [pmix/pmix-standard#83]
pp96:18: "the function will return when all participating processes have called 'connect'

It is not clear here what is a 'participating process', and who is required to call connect.

**Comment by abouteiller** [comment]
It may also be  worth clarifying that unlike  TCP/MPI, connect does both the 'connect' and the 'accept' side of the business.

**Comment by rhc54** [comment]
Will clarify - thx!

**Comment by rhc54** [comment]
Let me know if you think this still is an issue
