### ISSUE TITLE
Move section '6.4 Query'  into '7 Job control :: 7.1 Query'

### ISSUE THREAD

**Issue by abouteiller** [pmix/pmix-standard#86]
It appears that the functionality that are provided by section 6.4 are not really process-control centric, but more of a job-control nature. Listing the list of all namespaces, converting nodes and namespaces to proc names, etc. sounds like operations that compliment an introspection of the current allocation and other allocations and jobs. 

Proposal is to move the (unmodified) text to 7.1, job control, before the allocation extension and monitoring.

**Comment by jjhursey** [comment]
I don't have any objection to that. @rhc54 do you?
I think we put it in process management because those interfaces pre-datated the job allocation interfaces. But I can see the argument that the "Query" chapter makes more sense to be first in Chap 7.
