### ISSUE TITLE
Is     pmix_server_client_connected_fn_t   client_connected optional?

### ISSUE THREAD

**Issue by dsolt** [pmix/pmix-standard#9]
An RM implementation has liberty to define some of the functions in the pmix_server_module_2_0_0_t and not others.  Is there a base set of minimally required?  Are any of them paired (If you implement publish, lookup or unpublish then you must implement all of publish/lookup/unpublish).   

What about client_connected?    A server could do nothing except call the callback, but internally not need to record anything.  Is it still obligated to provide a simple implementation of client_connected or can it be NULL (meaning this server does not require notification when a client has connected)

**Comment by dsolt** [comment]
Sounds good.   I like that this particular one is optional.   Shall we leave this open as a discussion of other's as they come up and then we can close this issue once I get through all of them? :)

**Comment by rhc54** [comment]
Sure - no reason to proliferate issues 😄

**Comment by jjhursey** [comment]
Per teleconf:

In the Server chapter create 'groupings' of interfaces that are inter-related. Then call out that "if you support one of these, then you should support all of them."

In the Client chapter we will need to do the same maybe in the chapter heading (e.g., `PMIx_Get` and `PMIx_Put`). Need to be careful in the wording that these functions are related, and work together. Might need to be careful that if the job data contains everything you need then you might only need `PMIx_Get` and not `commit` or `put` (but not visa versa).

**Comment by rhc54** [comment]
Any progress on this? I was thinking that perhaps we can do it via the chapter organization - i.e., collect the groupings in a chapter and just explain that they should be supported as a group in the chapter's opening paragraph. Do we need anything further?

**Comment by jjhursey** [comment]
Per teleconf - we think the questions in this have been resolved.

'yes' was the answer to the title question. The 'grouping' portion of the discussion has been handled in the recent changes. We can reopen another ticket if we need further refinement.
